### ISSUE TITLE
Implement `Debug` + `Display` for builtins

### ISSUE THREAD

**Issue by lilizoey** [godot-rust/gdext#110]
NodePath doesn't implement debug, but it should. May be true for other types as well.

**Comment by Bromeon** [comment]
Yeah, a lot of core type functionality is missing, see https://github.com/godot-rust/gdextension/issues/6.
I renamed this issue to generally track `Debug`/`Display` for builtin types. 

Please don't open a new issue for each other trait, just comment here 🙂

**Comment by 0awful** [comment]
# Completeness:
## Structs
| name | debug | display |
| -- | -- | -- |
| AABB | [x] | [x] |
| Array | [x] | [ ] |
| Basis | [x] | [x] |
| Callable | [x] | [x] |
| Color | [x] | [x] |
| Dictionary | [x] | [ ] |
| GString | [x] | [x] |
| NodePath | [x] | [x] |
| PackedByteArray | [ ] | [ ] |
| PackedColorArray | [ ] | [ ] |
| PackedFloat32Array | [ ] | [ ] |
| PackedFloat64Array | [ ] | [ ] |
| PackedInt32Array | [ ] | [ ] |
| PackedInt64Array | [ ] | [ ] |
| PackedStringArray | [ ] | [ ] |
| PackedVector2Array | [ ] | [ ] |
| PackedVector3Array | [ ] | [ ] |
| Plane | [x] | [x] |
| Projection | [x] | [x] |
| Quarternion | [x] | [x] |
| Rect2 | [x] | [x] |
| Rect2i | [x] | [x] |
| Signal (incomplete) | [ ] | [ ] |
| StringName | [x] | [x] |
| Transform2D | [x] | [x] |
| Transform3D | [x] | [x] |
| Variant | [x] | [x] |
| Vector2 | [x] | [x] |
| Vector2i | [x] | [x] | 
| Vector3 | [x] | [x] |
| Vector3i | [x] | [x] |
| Vector4 | [x] | [x] |
| Vector4i | [x] | [x] |

## Enums
| Name | Debug | Display |
| -- | -- | -- |
| ColorChannelOrder | [x] | [ ] |
| EulerOrder | [x] | [ ] |
| ProjectionEye | [x] | [ ] |
| ProjectionPlane | [x] | [ ] |
| RectSide | [ ] | [ ] |
| Rid | [x] | [x] |
| VariantOperator | [x] | [ ] |
| VariantType | [x] | [ ] |
| Vector2Axis | [x] | [ ] |
| Vector3Axis | [x] | [ ] |
| Vector4Axis | [x] | [ ] |

**Comment by 0awful** [comment]
Does this include adding these functions for `real` and `VariantArray`? I think they should keep the impls from the types they wrap but I'm not sure.

**Comment by Bromeon** [comment]
Thanks a lot for listing all the impls!



> Does this include adding these functions for `real` and `VariantArray`? I think they should keep the impls from the types they wrap but I'm not sure.

Yes, they should keep the impl from their underlying types. You won't be able to write `impl`s here (for `real` because it's either `f32`/`f64`, and for `VariantArray` because it would overlap the `Array<T>` impl).

**Comment by 0awful** [comment]
@Bromeon Are you looking for `display` to be implemented on the enums as well?

**Comment by Bromeon** [comment]
No, I think it's fine to limit to the builtin types for now 🙂
