### ISSUE TITLE
When a panic happens inside of gdext, display the line number of the panic inside the Godot editor, instead of only the message

### ISSUE THREAD

**Issue by atrefonas** [godot-rust/gdext#170]
As discussed in Discord, this would improve the developer experience and help with debugging.

Right now it only displays the message but it would be very helpful to see the line number and .rs source code file as well.

![image](https://user-images.githubusercontent.com/72869083/224491245-deb672bc-7df9-4c8a-80d5-593ee1c3efd6.png)

**Comment by atrefonas** [comment]
Note that by setting RUST_BACKTRACE=1 you can (usually) see the back-traces in the terminal.

**Comment by Bromeon** [comment]
@atrefonas would you want to give this a try?

The relevant code is in `handle_panic`:

https://github.com/godot-rust/gdext/blob/eb30a8be983a160d6d0ec9d0b37265c503e3c2c3/godot-core/src/lib.rs#L69


We would probably need to set up a panic handler to get the panic location:
```rs
let mut location = ...; // not yet initialized

// Back up previous hook, set new one
let prev_hook = panic::take_hook();
panic::set_hook(Box::new(|panic_info| {
    // TODO get location out -- this may be a struggle
    location = ...;
}));

// Run code that should panic, restore hook
let panic = panic::catch_unwind(code);
panic::set_hook(prev_hook);

match panic {
    Ok(result) => Some(result),
    Err(err) => {
        log::godot_error!("Rust function panicked. Context: {}", error_context());
        // TODO print location in below function
        print_panic(err, location);
        None
    }
}
```
