### ISSUE TITLE
Static methods and custom constructors on custom types

### ISSUE THREAD

**Issue by HenryWConklin** [godot-rust/gdext#175]
Question/Feature Request

Is there a way to define methods on your custom types in Rust which do not take a `self` parameter? 

A minimal example of how I would expect it to work:
```
use godot::prelude::*;

#[derive(GodotClass)]
#[class(base=Object)]
pub struct MyType {
    pub foo: f32,
}

#[godot_api]
impl MyType {
    #[func]
    pub fn from_foo(foo: f32) -> Gd<MyType> {
        Gd::new(MyType { foo })
    }
}
```

But, I currently get a somewhat cryptic error from the macro:
```
error: no rules expected the token `foo`
   --> mycrate/src/lib.rs:125:21
    |
125 |     pub fn from_foo(foo: f32) -> Gd<MyType> {
    |                     ^^^ no rules expected this token in macro call

error: could not compile `mycrate` due to previous error
```

Use case for this would be static methods and constructors that actually take arguments. 
This would ideally be called from GdScript like `MyType.from_foo(foo)` which constructs a `MyType` from a `foo`.

There is https://github.com/godotengine/godot/issues/61963 which seems to suggest it's supported by gdextension, but I haven't found a way to do it in Rust using this repo.

There's also #43 which looks like the other direction, exposing static methods on Godot types in Rust.

**Comment by ttencate** [comment]
I have a PR (#210) that will make this compile, but it's blocked behind some other work (#204) that will actually make it useful. Right now it would probably either crash or leak if you tried anything nontrivial like returning a `Gd` type.
