### ISSUE TITLE
`#[export]` silently does not work without `#[godot_api]` impl

### ISSUE THREAD

**Issue by ttencate** [godot-rust/gdext#187]
E.g.

```rust
#[derive(GodotClass)]
#[class(base = RefCounted)]
struct MyStruct {
    #[export]
    int_val: i32,
}
```

The class itself gets registered, but its exports do not. Godot gives its customary error like "invalid get index int_val on base MyStruct".

This is probably a result of how/when generated code is invoked, but it would be nice if we could just make it work, error out at compile time, or as a last resort, warn at runtime.

**Comment by juliohq** [comment]
For some reason, it doesn't work:

```rust
#[derive(GodotClass)]
#[class(base=Resource)]
pub struct GameMatch {
    #[export]
    players: i64,

    #[base]
    base: Base<Resource>,
}

#[godot_api]
impl ResourceVirtual for GameMatch {
    fn init(base: Base<Resource>) -> GameMatch {
        GameMatch { players: 0, base }
    }
}
```

While this does:

```rust
#[derive(GodotClass)]
#[class(base=Resource)]
pub struct GameMatch {
    #[export]
    players: i64,

    #[base]
    base: Base<Resource>,
}

#[godot_api]
impl GameMatch {
    fn init(base: Base<Resource>) -> GameMatch {
        GameMatch { players: 0, base }
    }
}
```

At least, the former doesn't show `players` in the Godot's built-in docs, while the latter does.
