### ISSUE TITLE
Attempting to use `_input` will crash Godot

### ISSUE THREAD

**Issue by sayaks** [godot-rust/gdext#189]
Attempting to use `_input` will crash Godot, because we attempt to construct a `Gd<InputEvent>` directly from the pointer Godot sends us in the virtual call. However the pointer Godot sends us is actually a `Ref<InputEvent>`, which needs to be dereferenced using `ref_get_object` first.

A function defined on `Gd` like this does that properly
```rs
pub unsafe fn from_ref_sys(ptr: sys::GDExtensionConstRefPtr) -> Self {
    let object_ptr = interface_fn!(ref_get_object)(ptr);
    Self::from_obj_sys(object_ptr)
}
```

My guess is that this is true for all objects inheriting from `RefCounted` in virtual methods. But it doesn't seem like there's a simple way to check this beyond just manually going through every virtual method and checking. The `extension_api.json` doesn't say anything.

There isn't a simple hotfix for this beyond just expanding the macros and manually replacing the relevant call for `_input`. However doing so does fix the issue.

**Comment by sayaks** [comment]
Here:

https://github.com/godot-rust/gdext/blob/cccf2473000af973060d30e7d2bbdea915071f1d/godot-codegen/input/gdextension_interface.h#L157

**Comment by Bromeon** [comment]
Sorry, I meant not the type but the pointer value. You suggested `Gd::from_ref_sys()` -- but we don't have a pointer of type `sys::GDExtensionConstRefPtr` anywhere around, and there's no FFI function that returns one.

So I guess we would need to transmute a pointer from a different type (`sys::GDExtensionTypePtr`)...

**Comment by sayaks** [comment]
yeah, just like how we currently just cast a pointer to ObjectPtr in the virtual method calls.

**Comment by sayaks** [comment]
Actually it seems like we need to do this for *all* object pointers
