### ISSUE TITLE
`*Extension` classes missing virtual methods that accept or return pointers

### ISSUE THREAD

**Issue by lilizoey** [godot-rust/gdext#191]
`*Extension` classes often use pointers to interact with the engine. For instance, all of `PhysicsDirectSpaceState2D` except for the ones inherited from `Object` use pointers in various places.

We currently do not generate virtual methods that accept or return pointers. This makes many of these classes unusable, as key behavior is not available.

non-exhaustive list:
- [`PhysicsDirectSpaceState2D`](https://docs.godotengine.org/en/latest/classes/class_physicsdirectspacestate2d.html), 
  - all methods
- [`ScriptExtension`](https://docs.godotengine.org/en/latest/classes/class_scriptextension.html)
  - [`_instance_create`](https://docs.godotengine.org/en/latest/classes/class_scriptextension.html#class-scriptextension-method-instance-create)
  - [`_placeholder_instance_create`](https://docs.godotengine.org/en/latest/classes/class_scriptextension.html#class-scriptextension-method-placeholder-instance-create)
  - [`_placeholder_erased`](https://docs.godotengine.org/en/latest/classes/class_scriptextension.html#class-scriptextension-method-placeholder-erased)

**Comment by sayaks** [comment]
It seems that many of the `Extension` classes have virtual methods that either accept or return pointers. Which are currently excluded because they are usually supplementary, however in `Extension` classes they are generally not supplementary.

**Comment by Bromeon** [comment]
True, this was actually omitted by design for now, and can be added later:
https://github.com/godot-rust/gdext/blob/33c4e55ee78d9ccdd2bb7cf9ec24f5a9fd8889fd/godot-codegen/src/class_generator.rs#L476-L484

Reclassifying as feature request.
