### ISSUE TITLE
Class without `init` cannot be returned from Rust to GDScript

### ISSUE THREAD

**Issue by ttencate** [godot-rust/gdext#194]
```rust
#[derive(GodotClass)]
#[class]
pub struct World {
}

#[derive(GodotClass)]
#[class(init)]
pub struct WorldGen {
}

#[godot_api]
impl WorldGen {
    #[func]
    fn generate(&mut self) -> Gd<World> {
        Gd::new(World {})
    }
}
```

When calling `WorldGen.new().generate()` from GDScript, Godot prints an error:

    ERROR: Class 'World' has no native extension.
       at: set_object_extension_instance (core/object/class_db.cpp:356)

If I put `#[class(init)]` on World instead of bare `#[class]`, it starts working. Same if I manually implement `init` on `GodotExt`.

I did expect `World` not to be instantiable from GDScript or addable in the editor, but when instantiated from Rust it should still be possible tot pass it back to GDScript.

**Comment by lilizoey** [comment]
Checking the godot source-code, we need to set the `create_instance_func` in `GDExtensionClassCreationInfo` to be a null-pointer for godot to understand that a class cannot be instantiated:

```c++
bool ClassDB::can_instantiate(const StringName &p_class) {
	OBJTYPE_RLOCK;

	ClassInfo *ti = classes.getptr(p_class);
	ERR_FAIL_COND_V_MSG(!ti, false, "Cannot get class '" + String(p_class) + "'.");
#ifdef TOOLS_ENABLED
	if (ti->api == API_EDITOR && !Engine::get_singleton()->is_editor_hint()) {
		return false;
	}
#endif
	return (!ti->disabled && ti->creation_func != nullptr && !(ti->gdextension && !ti->gdextension->create_instance));
}
```

**Comment by lilizoey** [comment]
https://github.com/godotengine/godot/pull/58972 see also here for a guide on what abstract vs virtual means and such. but the basic point is that we do need to properly set our class as not being instantiable.

**Comment by Bromeon** [comment]
I just tested the original snippet. Nowadays, the API expects explicit `init` or `no_init`, and the error message is quite detailed if forgotten:
```rs
error[E0277]: Class `World` requires either an `init` constructor, or explicit opt-out
  --> itest/rust/src/register_tests/var_test.rs:27:12
   |
27 | pub struct World {
   |            ^^^^^ needs `init`
   |
   = help: the trait `GodotDefault` is not implemented for `World`
   = note: To provide a default constructor, use `#[class(init)]` or implement an `init` method
   = note: To opt out, use `#[class(no_init)]`
   = note: see also: https://godot-rust.github.io/book/register/constructors.html
```

So, after adding `no_init`, we have this updated code:
```rs
#[derive(GodotClass)]
#[class(no_init)]
pub struct World {}

#[derive(GodotClass)]
#[class(init)]
pub struct WorldGen {}

#[godot_api]
impl WorldGen {
    #[func]
    fn generate(&mut self) -> Gd<World> {
        Gd::from_object(World {})
    }
}
```

Now, calling from GDScript:
```gdscript
func test_world_gen():
    var w = WorldGen.new().generate()
    print(w)
```
This works as expected, prints `<RefCounted#-9223371997294098691>`.
The issue should thus be solved :beer:
