### ISSUE TITLE
Any way to make the compilation/testing faster?

### ISSUE THREAD

**Issue by juliohq** [godot-rust/gdext#202]
_I'm sorry for opening this issue, I'm not sure if this is the correct way to discuss about this topic_.

Right now the compilation process looks a bit slow. Do you think there's any way to speed it up somehow? Maybe avoiding useless recompilation?

**Comment by zoe-bat** [comment]
have you already tried using mold as a linker?

it's a pretty safe way to speed up rust compilation but still has some issues on anything that's not linux iirc

**Comment by juliohq** [comment]
> have you already tried using mold as a linker?
> 
> it's a pretty safe way to speed up rust compilation but still has some issues on anything that's not linux iirc

Not actually, but I'm trying it right now and looks to be way faster. And yes, I'm on Linux.

**Comment by Bromeon** [comment]
@juliohq out of curiosity, where exactly do you experience slowness? During incremental compilation, or just the initial one?

**Comment by juliohq** [comment]
> @juliohq out of curiosity, where exactly do you experience slowness? During incremental compilation, or just the initial one?

During incremental ones and `./check.sh`.

**Comment by sayaks** [comment]
> Also, commenting out those lines makes it `cargo build` 20% faster for a clean build:

do you know what impact it has on incremental build times?

**Comment by juliohq** [comment]
> > Also, commenting out those lines makes it `cargo build` 20% faster for a clean build:
> 
> do you know what impact it has on incremental build times?

2m 26s with `opt-level = 3`, 2m 11s with everything commented out. However I wouldn't take that as absolute, still need to check what the times are under different conditions I guess.

**Comment by Bromeon** [comment]
Very interesting, thanks for the feedback. Might be worth removing the special handling of those crates. Seems like the faster runtime does not make up for the extra compilation time needed for release mode.

Regarding `check.sh`, one problem is that the different subtasks may be compiled with slightly different compiler config, which requires needless recompilation. We can probably improve that too.

**Comment by Bromeon** [comment]
I removed those lines and allow for pre-generated bindgen in #211. There are still more places to optimize, like `check.sh`, but it might already help somewhat.

**Comment by juliohq** [comment]
@Bromeon sure, that has helped a lot though!

**Comment by Bromeon** [comment]
Good to hear! 🙂 
I'll close this, we can address future improvements in separate issues.
