### ISSUE TITLE
Error loading extension: res//DodgeTheCreeps.gdextension

### ISSUE THREAD

**Issue by mareksubocz** [godot-rust/gdext#208]
I've tried to run DodgeTheCreeps demo on M1 Macbook Pro. The project built and the game started, but nothing happened after clicking the "START" button inside the game and following errors appeared:

```
Can't open dynamic library: /Users/mareksubocz/it/gdext/examples/dodge-the-creeps/godot/../../../target/debug/libdodge_the_creeps.dylib, error: dlopen(/Applications/Godot.app/Contents/MacOS/../Frameworks/libdodge_the_creeps.dylib, 0x0002): tried: '/Applications/Godot.app/Contents/MacOS/../Frameworks/libdodge_the_creeps.dylib' (no such file).
  core/extension/gdextension.cpp:400 - GDExtension dynamic library not found: /Users/mareksubocz/it/gdext/examples/dodge-the-creeps/godot/../../../target/debug/libdodge_the_creeps.dylib
  Failed loading resource: res://DodgeTheCreeps.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
  Can't open dynamic library: /Users/mareksubocz/it/gdext/examples/dodge-the-creeps/godot/../../../target/debug/libdodge_the_creeps.dylib, error: dlopen(/Applications/Godot.app/Contents/MacOS/../Frameworks/libdodge_the_creeps.dylib, 0x0002): tried: '/Applications/Godot.app/Contents/MacOS/../Frameworks/libdodge_the_creeps.dylib' (no such file).
  core/extension/gdextension.cpp:400 - GDExtension dynamic library not found: /Users/mareksubocz/it/gdext/examples/dodge-the-creeps/godot/../../../target/debug/libdodge_the_creeps.dylib
  Failed loading resource: res://DodgeTheCreeps.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
```

The steps I took to set the project up were:
```
brew install godot
git clone https://github.com/godot-rust/gdext && cd gdext
export GODOT4_BIN=/Applications/Godot.app/Contents/MacOS/Godot
export LLVM_PATH=/Library/Developer/CommandLineTools/usr/bin
cargo build # successfully
cd examples/dodge-the-creeps
cargo build # successfully
godot # to run the game
```

Is there something I overlooked?

**Comment by Bromeon** [comment]
Could you check the contents of the directory `gdext/examples/dodge-the-creeps/godot/../../../target/debug`?

Also, try specifically `cargo build -p dodge-the-creeps` (although that shouldn't be necessary).

**Comment by mareksubocz** [comment]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/36044757/228219077-13ff4b50-8e66-494b-8846-2feba79ab949.png">

Also, ```cargo build -p dodge-the-creeps``` didn't fix anything.

**Comment by Bromeon** [comment]
Is there only the dynamic library for `godot_macros`? 
Why not for `godot`?

**Comment by sayaks** [comment]
try to cd into `examples/dodge-the-creeps/rust` before building

**Comment by Bromeon** [comment]
Can you do the following, and paste the full command line + output?
Navigate to the `gdext` directory, then:
```bash
rm -rf target
cargo update
cargo build
ls -la target/debug
```

**Comment by mareksubocz** [comment]
> try to cd into `examples/dodge-the-creeps/rust` before building

That didn't change anything.

> Can you do the following, and paste the full command line + output? Navigate to the `gdext` directory, then:
> 
> ```shell
> rm -rf target
> cargo update
> cargo build
> ls -la target/debug
> ```

➜  gdext git:(master) ✗ rm -rf target
➜  gdext git:(master) ✗ cargo update
    Updating crates.io index
➜  gdext git:(master) ✗ cargo build
   Compiling libc v0.2.140
   Compiling proc-macro2 v1.0.54
   Compiling quote v1.0.26
   Compiling unicode-ident v1.0.8
   Compiling nanoserde-derive v0.1.19
   Compiling regex-syntax v0.6.29
   Compiling glob v0.3.1
   Compiling memchr v2.5.0
   Compiling either v1.8.1
   Compiling minimal-lexical v0.2.1
   Compiling clang-sys v1.6.0
   Compiling cfg-if v1.0.0
   Compiling syn v1.0.109
   Compiling heck v0.4.1
   Compiling nanoserde v0.1.32
   Compiling which v4.4.0
   Compiling nom v7.1.3
   Compiling libloading v0.7.4
   Compiling bindgen v0.63.0
   Compiling regex v1.7.3
   Compiling godot-codegen v0.1.0 (/Users/mareksubocz/it/gdext/godot-codegen)
   Compiling cexpr v0.6.0
   Compiling rustc-hash v1.1.0
   Compiling lazycell v1.3.0
   Compiling shlex v1.1.0
   Compiling lazy_static v1.4.0
   Compiling bitflags v1.3.2
   Compiling peeking_take_while v0.1.2
   Compiling paste v1.0.12
   Compiling venial v0.5.0
   Compiling once_cell v1.17.1
   Compiling getrandom v0.2.8
   Compiling glam v0.22.0
   Compiling rand_core v0.6.4
   Compiling ppv-lite86 v0.2.17
   Compiling rand_chacha v0.3.1
   Compiling itest v0.1.0 (/Users/mareksubocz/it/gdext/itest/rust)
   Compiling rand v0.8.5
   Compiling godot-macros v0.1.0 (/Users/mareksubocz/it/gdext/godot-macros)
   Compiling godot-core v0.1.0 (/Users/mareksubocz/it/gdext/godot-core)
   Compiling godot-ffi v0.1.0 (/Users/mareksubocz/it/gdext/godot-ffi)
   Compiling godot v0.1.0 (/Users/mareksubocz/it/gdext/godot)
   Compiling dodge-the-creeps v0.1.0 (/Users/mareksubocz/it/gdext/examples/dodge-the-creeps/rust)
    Finished dev [unoptimized + debuginfo] target(s) in 44.07s
➜  gdext git:(master) ✗ ls -la target/debug
total 3544
drwxr-xr-x   10 mareksubocz  staff      320 Mar 28 14:35 .
drwxr-xr-x@   6 mareksubocz  staff      192 Mar 28 14:35 ..
-rw-r--r--    1 mareksubocz  staff        0 Mar 28 14:34 .cargo-lock
drwxr-xr-x   52 mareksubocz  staff     1664 Mar 28 14:34 .fingerprint
drwxr-xr-x   21 mareksubocz  staff      672 Mar 28 14:34 build
drwxr-xr-x  239 mareksubocz  staff     7648 Mar 28 14:34 deps
drwxr-xr-x    2 mareksubocz  staff       64 Mar 28 14:34 examples
drwxr-xr-x    7 mareksubocz  staff      224 Mar 28 14:34 incremental
-rw-r--r--    1 mareksubocz  staff      408 Mar 28 14:35 libgodot_macros.d
-rwxr-xr-x    1 mareksubocz  staff  1808051 Mar 28 14:34 libgodot_macros.dylib
<img width="759" alt="image" src="https://user-images.githubusercontent.com/36044757/228238219-f32d7c93-7d80-4ceb-bf09-2b31b510da70.png">

**Comment by mareksubocz** [comment]
Nice! That got rid of the problem, thank you so much!

I suspect however there is another thing to solve, the sprites don't display properly:
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/36044757/228251206-90fc2e70-6a96-4a1e-aef5-5385ab73dcf9.png">

**Comment by Bromeon** [comment]
> Nice! That got rid of the problem, thank you so much!

Which architecture was it? How does your `.gdextension` file look now?

Btw, you should also be able to get the name through [`Engine::get_architecture_name`](https://docs.godotengine.org/en/stable/classes/class_engine.html#class-engine-method-get-architecture-name).

> I suspect however there is another thing to solve, the sprites don't display properly:

Can you open the editor once, save all scenes and see if anything changes?
From the command line, you can navigate to the `dodge-the-creeps/godot` directory and run `godot4 -e`.

**Comment by Bromeon** [comment]
Also changing the scenes slightly (in insignificant ways) + saving doesn't update the files? You should see changes in `git diff` for `Mob.tscn` and `Player.tscn`...

**Comment by mareksubocz** [comment]
It does update the files, but the warnings stil remain. I'm not sure if Player.tsch is updated, as it is not present in ```git diff```.

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/36044757/228258565-ef78ec6f-d233-4371-bb51-7170d98be7f0.png">

**Comment by mareksubocz** [comment]
I am currently using the latest commit. I don't know what those hashes mean, but i reverted all changes and compiled everything again and, despite still seeing some warnings, everything worked and I was able to play the game! Thank you so much :D Love the support of this project! The issue is ready to close.
