### ISSUE TITLE
Reimplement `Rect2`, `Rect2i`, `Aabb`, and `Plane` in rust

### ISSUE THREAD

**Issue by lilizoey** [godot-rust/gdext#209]
Currently, [`Rect2`](https://github.com/godot-rust/gdext/blob/master/godot-core/src/builtin/rect2.rs), [`Rect2i`](https://github.com/godot-rust/gdext/blob/master/godot-core/src/builtin/rect2i.rs), [`Aabb`](https://github.com/godot-rust/gdext/blob/master/godot-core/src/builtin/aabb.rs), and [`Plane`](https://github.com/godot-rust/gdext/blob/master/godot-core/src/builtin/plane.rs) have only a very simple implementation, requiring users to use `InnerX` to call most methods on them. We should reimplement these in rust, along the lines of the other mathematical types.

Have a look at for instance [`Vector2`](https://github.com/godot-rust/gdext/blob/master/godot-core/src/builtin/vector2.rs) and [`Basis`](https://github.com/godot-rust/gdext/blob/master/godot-core/src/builtin/basis.rs) to see what this should look like.

Another good source for inspiration is our gdnative bindings, they can be found here: [`Rect2`](https://github.com/godot-rust/gdnative/blob/master/gdnative-core/src/core_types/geom/rect2.rs), [`Aabb`](https://github.com/godot-rust/gdnative/blob/master/gdnative-core/src/core_types/geom/aabb.rs), [`Plane`](https://github.com/godot-rust/gdnative/blob/master/gdnative-core/src/core_types/geom/plane.rs)

In addition unit tests and integration tests would be needed. 

For unit tests it can be useful to look at godot's unit tests for the same types, they can be found [here](https://github.com/godotengine/godot/tree/master/tests/core/math).

For integration tests, [basis_test.rs](https://github.com/godot-rust/gdext/blob/master/itest/rust/src/basis_test.rs) is a good example to go by, something like `basis_equiv` is a minimum to ensure our methods behave similarly to godot.

Finally, for writing documentation and ensuring you're covering all methods we want, look at the godot docs for the various types: [Rect2](https://docs.godotengine.org/en/stable/classes/class_rect2.html), [Rect2i](https://docs.godotengine.org/en/stable/classes/class_rect2i.html), [Aabb](https://docs.godotengine.org/en/stable/classes/class_aabb.html) and [Plane](https://docs.godotengine.org/en/stable/classes/class_plane.html).

Not everything has to be done at once.

## Reimplemented so far:

- [ ] Rect2 #242 
- [x] Rect2i
- [x] Aabb #280 
- [x] Plane #268

**Comment by Cankyre** [comment]
Aabb is done, you can mark it as closed. #280

**Comment by Bromeon** [comment]
Will close automatically when #242 is merged.
