### ISSUE TITLE
`Theme Overrides` missing in inspector for Rust control-based nodes

### ISSUE THREAD

**Issue by Arrekin** [godot-rust/gdext#213]
Some control-based nodes like HBoxContainer or Panel have a `Theme Overrides` field in the inspector(last entry under `Control` block).
If we create a Rust class "inheriting" from those Godot nodes, that field does not show anymore in the inspector.

Example:
(On the left is Godot's original HBoxContainer, and to the right, a custom class inheriting from it.)
![image](https://user-images.githubusercontent.com/11314775/229864470-8456abb6-83fa-43dd-ac5f-1f788ea3e730.png) ![image](https://user-images.githubusercontent.com/11314775/229864567-8e7bc1bf-2d39-4bea-88df-4741f620e246.png)

Example of Godot docs mentioning theme override properties: https://docs.godotengine.org/en/stable/classes/class_hboxcontainer.html#theme-properties

The overriding itself works fine, for example, if we add a ready() function to our Rust class: 
```
fn ready(&mut self) {
    self.add_theme_constant_override("separation".into(), 200);
}
```
Our box node will consider it and properly space the items. It will still not show in the inspector but that is expected(setting custom constants from GDScripts will not propagate them to the inspector. `Theme Overrides` in the inspector shows only for the properties baked into the node(the ones that are present in the node documentation).

I see two options(from outside as I have no knowledge of implementation details neither of GDExt or Godot): Either there is some issue with propagating/reporting those properties to the inspector, or maybe they are not set at all for Rust inherited classes. The `Theme Overrides` will not show in the inspector if there are no properties to override(For example the basic Control node does not have this field).

I prepared a minimal example(Rust & Godot). It contains a scene where you can observe the same as what the screens above are showing: 
[theme-overrides-minimal.zip](https://github.com/godot-rust/gdext/files/11151150/theme-overrides-minimal.zip)
(GDExtension contains only .dll entry for Windows, you may need .so line if you are on Linux)

**Comment by lilizoey** [comment]
theme overrides is defined in `_get_property_list`. we might need to auto-generate an implementation of that that just calls the super class' implementation of the virtual method?

**Comment by Bromeon** [comment]
Does that method not list all the properties by default?

Implementing a virtual method just to call the parent impl contradicts the idea of virtual methods -- but maybe that's indeed a weird quirk of Godot?

**Comment by lilizoey** [comment]
> Does that method not list all the properties by default?
> 
> Implementing a virtual method just to call the parent impl contradicts the idea of virtual methods -- but maybe that's indeed a weird quirk of Godot?

no it is used to add additional properties to the default properties, it is not used for all properties. similar to how we register our properties without using that virtual method.

**Comment by Bromeon** [comment]
Good naming strikes again...
Thanks for elaboration!

**Comment by grtwje** [comment]
I was seeing this with 4.1.3. After upgrading to 4.2 the theme overrides started appearing in the Editor.

**Comment by coder137** [comment]
> I was seeing this with 4.1.3. After upgrading to 4.2 the theme overrides started appearing in the Editor.

@grtwje Did you do something specific, Made a GDExtension class from MarginContainer and can't see the theme overrides.

**Comment by grtwje** [comment]
@coder137 Maybe it seemed to "work" for me because I had already manually edited the tscn file in 4.1.3, and the edit triggered something in 4.2 to make the theme overrides show up in the 4.2 Editor. There's a Discord post on my edits, [gdext](https://discordapp.com/channels/723850269347283004/1043514894198255737/1183547263839125544).

**Comment by rymkapro** [comment]
Encountered the same issue, even in godot 4.2

**Comment by tropical32** [comment]
This is now showing up for me in 4.3. Can someone confirm?

**Comment by Bromeon** [comment]
@Arrekin @grtwje @coder137 @rymkapro?

**Comment by coder137** [comment]
Just checked with one two nodes and yes, Theme overrides now show up
