### ISSUE TITLE
Vector3 missing a rotated method

### ISSUE THREAD

**Issue by Supreeeme** [godot-rust/gdext#221]
Was following through the squash the creeps tutorial and noticed that Vector3 is missing a rotated method, although it has one in Godot. Is this intentional?

**Comment by Bromeon** [comment]
No, probably an oversight or simply not yet implemented.
Did you encounter other missing parts in `Vector3`?

Would you be interested in adding the method in a pull request? 🙂

**Comment by Supreeeme** [comment]
I'm not confident in my vector math abilities but I could certainly try and make an attempt sometime soon :slightly_smiling_face:

**Comment by Bromeon** [comment]
For inspiration, you can have a look at the [Godot implementation](https://github.com/godotengine/godot/blob/master/core/math/vector3.cpp#L42-L46) 🙂 

We generally try to benefit from geometric types' `Copy` trait and thus return new objects. As such, we would only need `rotated()` and not `rotate()`.

If you find other related methods, feel free as well!
