### ISSUE TITLE
Exporting typed array of resources has null defaults in the editor and no class constraints

### ISSUE THREAD

**Issue by jfaz1** [godot-rust/gdext#230]
When exporting a resource with `#[export]`, e.g:

```rust
#[export]
resource: Array<Gd<EditorSettings>>
```

The editor defaults to null values, and doesn't know what class it should pick from when adding new elements:
![image](https://user-images.githubusercontent.com/56184947/232254256-31988312-9c26-40f7-a55d-6a60f19b7536.png)

If you do the same in `gdscript`, the defaults are `<empty>` instead of `<null>`, and it gives you the class:
![image](https://user-images.githubusercontent.com/56184947/232254287-88cec558-bf93-4af2-b64c-ad7bec20c9ee.png)

It also enforces the specified type by setting the class back to what the type is if you select a different one.

It's an issue for a couple of reasons, but it in general it just makes it clunky and tedious adding new resource elements in the editor since you have to set the type to object, and then set the object to the resource class (which involves scrolling through every object in the engine, no way to search).

**Comment by sayaks** [comment]
i suspect this is caused by our [VariantMetadata impl for Gd](https://github.com/godot-rust/gdext/blob/885bb91926c76867093d85208b33aa80c87183b6/godot-core/src/obj/gd.rs#L707) not giving proper type information when the object Inherits from Resource
