### ISSUE TITLE
No docs for rust classes

### ISSUE THREAD

**Issue by bend-n** [godot-rust/gdext#258]
https://user-images.githubusercontent.com/70787919/236376594-bf89d94a-8ed9-4c68-9e17-3ba4ff0cf95d.mp4

`NEAT` is a rust class extending `RefCounted`, and the doc page is just empty.

Godot version [`8c729f0f3`](https://github.com/godotengine/godot/commit/8c729f0f3)

**Comment by Bromeon** [comment]
Is this not the exact same issue you reported under #178?

**Comment by bend-n** [comment]
No i dont think so, its supposed to like say `(no base) function (String, int) -> int` or something?

**Comment by lilizoey** [comment]
yeah, you can open documentation for custom rust classes in godot just fine. but this seems like clicking on that type in the docs for a different class/method doesn't lead you to the docs for the class? which is weird.

**Comment by bend-n** [comment]
Actually some of the video seems to have cut, i opened the class searcher, to search for `NEAT`, but it wasnt there.

**Comment by lilizoey** [comment]
> Actually some of the video seems to have cut, i opened the class searcher, to search for `NEAT`, but it wasnt there.

is this with the repo you have on your github?

**Comment by bend-n** [comment]
It is, i specified the commit hash in the main description. its also prebuilt, so the artifacts are [here](https://github.com/bend-n/godot-builds/actions/runs/4877181533). There shouldnt be a difference from official though as thats the normal build, which only turns off deprecated code and applys a patch or 2.

**Comment by lilizoey** [comment]
i thought the hash in the main description was for godot not your repo

**Comment by bend-n** [comment]
It builds godot with patches and options, it doesnt fork godot.

**Comment by lilizoey** [comment]
i think this is an upstream bug. it seems godot recently made some big changes in master to how documentation is generated. (see for instance https://github.com/godotengine/godot/pull/72095, there are also other commits that impact doc-gen). and this issue does not show up on 4.1 dev 1. but it shows up in at least two different recently built godot builds.

but i havent quite been able to find out exactly why this is broken here but i dont think this is an issue with our bindings.

**Comment by bend-n** [comment]
Ill see if i can bisect.

**Comment by bend-n** [comment]
Bisected, im told [53191928e597d15a709b53abe1870b9f3607af1c](https://github.com/godotengine/godot/commit/53191928e597d15a709b53abe1870b9f3607af1c) caused it. Quite a few regressions that PR caused!

**Comment by Bromeon** [comment]
Thanks a lot for investigating! 👍

Do you know if there's already an issue in the `godot` repo that tracks this docs problem?
If not, would you want to open one, to raise awareness?

**Comment by RedMser** [comment]
The upstream issue https://github.com/godotengine/godot/issues/76796 was fixed recently, this can maybe be closed now?

**Comment by Bromeon** [comment]
@RedMser have you tested that Rust classes show up in the editor? :slightly_smiling_face:

In the future we could maybe allow `///` comments to be used as documentation, but could also be in a new issue.

**Comment by RedMser** [comment]
> have you tested that Rust classes show up in the editor? 🙂

It does seem to work for me on 4.3 latest master yes.

> In the future we could maybe allow `///` comments to be used as documentation, but could also be in a new issue.

Seems to already be a separate issue here: #178

**Comment by Bromeon** [comment]
You're right. Thank you! 👍
