### ISSUE TITLE
Feature: Allow to define custom icon for Rust-based nodes

### ISSUE THREAD

**Issue by Arrekin** [godot-rust/gdext#277]
Godot allows to define a custom icon for named classes via `@icon()` annotation. 
I'd like it to be also supported in `gdext`, so I can customize the display of my Rust-based nodes in the editor

Relevant Godot documentation: https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#registering-named-classes

**Comment by lilizoey** [comment]
This is something we don't need to do anything with: https://github.com/godotengine/godot/pull/75472

So in 4.1, adding an icon to a class is simply adding entries to the `.gdextension` file like: 
```toml
[icons]
Threen = "res://bin/icon_tween.svg"
```

**Comment by Bromeon** [comment]
> We should probably keep this issue open at least until 4.1 is released though.

We're generally orienting gdext towards Godot's `master` branch. Therefore, since that PR is merged, I'd probably mark this closed. The alternative would be to wait for the release (and likely forget about this issue). Should anything change unexpectedly, we can always reopen.

**Comment by sanpii** [comment]
> This is something we don't need to do anything with: [godotengine/godot#75472](https://github.com/godotengine/godot/pull/75472)

This method only works for extensions, it isn’t available for component libraries. It would be useful to have the `@icon` annotation.

**Comment by TitanNano** [comment]
@sanpii what do you mean by "component libraries"?

**Comment by sanpii** [comment]
> [@sanpii](https://github.com/sanpii) what do you mean by "component libraries"?

Small reusable pieces of code. Something like that: https://github.com/bluematt/godot4-components/

**Comment by TitanNano** [comment]
> Small reusable pieces of code. Something like that: https://github.com/bluematt/godot4-components/

But this is not a "thing" in Godot isn't it? You can create a plugin which doesn't have an icon, or you can just create classes which can have an icon. "component libraries" can add icons to their classes, either by using GDScript classes or rust-based classes and adding the icon to the GDExtension.

Or are you looking for a way to create a rust library that exports Godot classes which can be added to someone else's rust based GDExtension?

**Comment by sanpii** [comment]
> But this is not a "thing" in Godot isn't it?

That adds new node type in godot.

> "component libraries" can add icons to their classes, either by using GDScript classes or rust-based classes and adding the icon to the GDExtension.

If I create a crate for these classes and use it in an extension, I don’t find how to add an icon for them. Maybe I miss something?

**Comment by Bromeon** [comment]
> If I create a crate for these classes and use it in an extension,

But why do you as a _user_ of the classes want to create an icon for them? This is responsibility of those who create the class (for GDExtension classes, those who register it).

I don't really see what exactly godot-rust should do in such a case, can you be concrete about the functionality?

**Comment by sanpii** [comment]
@Bromeon I think I understand where the misunderstanding comes from: my crate (which contains new classes) isn't a godot plugin, it used in my game (which is an extension).

In this configuration, I don’t have `.gdextension` at crate level.

**Comment by TitanNano** [comment]
@sanpii I see. But how do you get the crates class icons into the target Godot project? Godot needs an absolute path to the icon (absolute from the project root). 

`GDExtensionClassCreationInfo4` now actually supports `icon_path`s, but I don't see how you could properly utilize it. The way Godot expects you to do this, is to have two separate `GDExtensions` that interact with each other through the engine. I know this is not really supported by gdext yet.

**Comment by Bromeon** [comment]
The library dependency is indeed a problem, see #615.

But apart from that, can we not specify an icon path that's forwarded to the class registration?
Could be something like
```rs
#[derive(GodotClass)]
#[class(icon = "res://path/to/icon.png")]
struct MyClass {}
```

The out-of-band mapping in `.gdextension` isn't that great in my opinion.

**Comment by TitanNano** [comment]
> But apart from that, can we not specify an icon path that's forwarded to the class registration?
Could be something like

Yes I think we should definitely do that. Just regarding the use-case of @sanpii, I didn't think it would help him specifically.

Should we reopen this issue or create a new one?

**Comment by Bromeon** [comment]
Opened https://github.com/godot-rust/gdext/issues/1200 🙂
