### ISSUE TITLE
Crash when comparing Variants

### ISSUE THREAD

**Issue by LeaoLuciano** [godot-rust/gdext#287]
Comparing comparing two Gd<Script> as Variant causes a crash.

![image](https://github.com/godot-rust/gdext/assets/56130740/f55dddec-ff1f-4103-b61f-6b741637253c)

![image](https://github.com/godot-rust/gdext/assets/56130740/6bfba34d-cf0e-4e56-9a38-887f9113f490)

Ps: Crash don't occur when uncommenting line 26

**Comment by LeaoLuciano** [comment]
There is also no crash if  change line 27 to
```rust
 if node.get_script().to::<Gd<Script>>() == script {
```

**Comment by Bromeon** [comment]
Thanks! Do you have a minimal code that reproduces the problem?
Ideally in the form of something like `#[itest]` test cases as defined [here](https://github.com/godot-rust/gdext/blob/master/itest/rust/src/variant_test.rs)?

That would make it much easier for us to reproduce the issue.

**Comment by lilizoey** [comment]
Could you check if this happens if you use #285?

**Comment by LeaoLuciano** [comment]
> Could you check if this happens if you use #285?
> 
> i.e replace your dependency with:
> 
> ```toml
> [dependencies]
> godot = { git = "https://github.com/lilizoey/gdextension", branch = "feature/cfg-godot-version" }
> ```

This solves the crash.
