### ISSUE TITLE
derive To/From Variant on T : ToVariant? will not play nicely with skip feature.

### ISSUE THREAD

**Issue by astrale-sharp** [godot-rust/gdext#289]
Hi,

consider the following code 
```rust
#[derive(Debug, Clone, Default, ToVariant, FromVariant)]
pub struct Resettable<T> {
    default_value: T,
    value: T,
}
impl<T: Clone> Resettable<T> {}

```
Currently it complains that T doesn't impl to variant which is
+ Good when you want to skip T (will be useful for me in the future)
+ bad cause if you don't skip T cause then you have to write `Resettable<T : ToVariant + FromVariant>` and `impl<T: Clone + ToVariant + FromVariant> Resettable<T> {}` everywhere.

Proposed solution (that i can work on implementing):
implementing To/From Variant for T where T is From/To Variant except if T is skipped.

**Comment by Bromeon** [comment]
> Proposed solution (that i can work on implementing):
> implementing To/From Variant for T where T is From/To Variant except if T is skipped.

I don't think a `To/FromVariant` derive on a struct should implicitly derive those traits also for types appearing as fields. This would be very confusing.

I'm not 100% sure if I understand your problem, could you not write
```rs
pub struct Resettable<T: ToVariant + FromVariant> { ... }
```
to signal that _every_ `Resettable` has fields that fulfill these bounds?

**Comment by lilizoey** [comment]
I would expect it to work like most other derives do, and just generate a trait impl like `impl<T: ToVariant> ToVariant for Resettable<T> {}`.

**Comment by Bromeon** [comment]
@astrale-sharp do you think the suggestion from lilizoey could be a way to go?

**Comment by astrale-sharp** [comment]
I think the suggestion from lilizoey is the way to go indeed, I'll make a quick pr soon to set it like that

**Comment by Bromeon** [comment]
So, is there any concrete actionable on our side to achieve that? Otherwise I'll close this issue...

**Comment by Bromeon** [comment]
I'll take this as a "no" 😀

**Comment by astrale-sharp** [comment]
Yea sorry ^^'
