### ISSUE TITLE
No way to get Gd<Self> without casting

### ISSUE THREAD

**Issue by MatrixDev** [godot-rust/gdext#302]
AFAIK the only way to get `Gd<Self>` is to use base as `base.share().cast()`.

```rust
impl NoiseEmitter {
    fn f_ready(&mut self) {
        self.get_character().bind_mut().noise_emitter = Some(self.base.share().cast());
    }
}
```

But not taking to account cast overhead this is not safe and can lead to runtime bugs that ideally should be caught during compilation:

```rust
impl NoiseEmitter {
    fn f_ready(&mut self) {
        // notice that the field is '_receiver', but we're assigning '_emitter'
        self.get_character().bind_mut().noise_receiver = Some(self.base.share().cast());
    }
}
```

It would be nice if `#[derive(GodotClass)]` automatically generated Self-typed `share` method for such cases:

```rust
// generated
impl GodotClass for NoiseEmitter {
    pub fn share(&self) -> Gd<Self> {
        // TODO, ideally implemented without casting overhead but this is nitpicking
    }
}
```

**Comment by Bromeon** [comment]
Thanks for the use case and description!
Something along those lines was the 2nd suggestion in https://github.com/godot-rust/gdext/issues/131.

**Comment by Bromeon** [comment]
Implemented as `self.to_gd()`.

#497
