### ISSUE TITLE
Release mode no longer possible?

### ISSUE THREAD

**Issue by dydokamil** [godot-rust/gdext#304]
I created two copies of this repository, extracted the examples directory, and built "dodge the creeps" in both the debug mode and the release mode. 

* In the first copy, I built this commit: 32f0efcaec8dcb39b3771e2b5182a4c343370ef5, which seems to be the last one on which the release build works
  * godot = { git = "https://github.com/godot-rust/gdext", rev = "32f0efcaec8dcb39b3771e2b5182a4c343370ef5" }
* In the second copy, I built this commit: 29a4fa7d3e0128e6ce4456f12fb8ebd00e1f1a05 
  * godot = { git = "https://github.com/godot-rust/gdext", rev = "29a4fa7d3e0128e6ce4456f12fb8ebd00e1f1a05" }
* I built both libraries using `cargo build && cargo build --release`
* I updated both `DodgeTheCreeps.gdextension` to point to the rust directory

```
[libraries]
linux.debug.x86_64 = "res://../rust/target/debug/libdodge_the_creeps.so"
linux.release.x86_64 = "res://../rust/target/release/libdodge_the_creeps.so"
```

* When exporting 32f0efcaec8dcb39b3771e2b5182a4c343370ef5 with the "Export with Debug" flag selected there is no issue.
* When exporting 32f0efcaec8dcb39b3771e2b5182a4c343370ef5 without the "Export with Debug" flag selected there is no issue.
* When exporting 29a4fa7d3e0128e6ce4456f12fb8ebd00e1f1a05 with the "Export with Debug" flag selected there is no issue.
* When exporting 29a4fa7d3e0128e6ce4456f12fb8ebd00e1f1a05 without the "Export with Debug" flag selected there is an error when running the game:

```
$ ./Dodge\ the\ Creeps.x86_64                                                                                                                  
Initialize GDExtension API for Rust: Godot Engine v4.0.3.stable.official
Godot Engine v4.0.3.stable.official.5222a99f5 - https://godotengine.org
Vulkan API 1.3.246 - Forward Mobile - Using Vulkan Device #0: AMD - AMD Radeon RX 6400 (RADV NAVI24)
 
[1]    55980 segmentation fault (core dumped)  ./Dodge\ the\ Creeps.x86_64
```

**Comment by lilizoey** [comment]
Minimal reproduction project:

```rs
use godot::prelude::*;

#[derive(GodotClass)]
#[class(init, base = Node)]
pub struct Mini {}

#[godot_api]
impl Mini {
    #[func]
    fn foo(&self, text: GodotString) {
        godot_print!("foo")
    }
}

struct Testing;

#[gdextension]
unsafe impl ExtensionLibrary for Testing {}
```

**Comment by lilizoey** [comment]
The arguments info array in the `#[godot_api]` are created like this:
```rs
let mut arguments_info: [sys::GDExtensionPropertyInfo; NUM_ARGS] = {
    use godot::builtin::meta::*;
    let mut i = -1i32;
    [{
        i += 1;
        let prop = <((), GodotString) as VarcallSignatureTuple>::property_info(
            i,
            stringify!(text),
        )
        .property_sys();
        prop
    }]
};
```
which is wrong. Since here `prop` becomes a `PropertyInfo`, then we return a pointer to `prop` using `property_sys()`. Which is then freed after this block ends. i imagine debug ends up not freeing this data or something before it's actually used, and it works, but in release this is almost certainly gonna get optimized out as it's UB.

**Comment by dydokamil** [comment]
This issue got reintroduced with eafcd91694cb4d40cd4dc6e2639cb233c2a98f7a

**Comment by lilizoey** [comment]
that's what we get for not adding a release build to the ci... im guessing it's something similar to last time. I'll check it out later today.

**Comment by lilizoey** [comment]
i think i've found the bug, it does indeed seem to be a similar issue to last time.
