### ISSUE TITLE
Array<T> is exported wrongly as Array, instead of Array[T]

### ISSUE THREAD

**Issue by kulkalkul** [godot-rust/gdext#324]
Rust:
![image](https://github.com/godot-rust/gdext/assets/1013994/3c657ac3-6754-4da6-833e-6c857a555685)
Godot:
![image](https://github.com/godot-rust/gdext/assets/1013994/cdb3121d-8123-4466-a4cc-b92e19315396)

**Comment by lilizoey** [comment]
are you sure it's actually exported wrongly and it's not just the documentation that's wrong?

**Comment by kulkalkul** [comment]
Depends on the meaning of the "export" I guess? It works as it should but no type inference, so I suppose only the type information is wrong. "exported wrongly" might be misnomer in that case

**Comment by lilizoey** [comment]
GDScript does the same thing interestingly
```gdscript
class_name Foo extends Node

func my_func(arr: Array[int]) -> Array[int]:
	return arr
```
![image](https://github.com/godot-rust/gdext/assets/9107253/eb6946ff-bddd-4353-9362-9fa6cc0b4b68)

**Comment by lilizoey** [comment]
We can fix this by making the `PropertyInfo` of a type be different between methods/returns and fields. Since if we make the hint `PROPERTY_HINT_ARRAY_TYPE` with the hint string being the name of the type the array contains, then the docs will properly display `Array[type]`.

**Comment by kulkalkul** [comment]
Hmm, weird why gdscript does that. For example, built-in methods like get_children show the correct signature, Array[Node].

I think it would be better if the type hint also reflects the actual type. I don't know if that's intended or not. I have no serious experience with either gdext or godot. I can only talk about DX in this case 😅

**Comment by Bromeon** [comment]
Even though Godot addressed it upstream, there was another bug on our side, which I now fixed as well :slightly_smiling_face:
