### ISSUE TITLE
Classname Alias

### ISSUE THREAD

**Issue by Hapenia-Lans** [godot-rust/gdext#332]
In godot engine, each class should have unique name, since their's no `mod`/`package`/`namespace`. But in rust, we can have multiple structs with a same name (in different mods). When you try to export two or more structs with the same name to Godot, a very subtle runtime error occurs. If you don't start the editor from the command line, you won't see the error message.

<img width="853" alt="image" src="https://github.com/godot-rust/gdext/assets/93276898/a5e8a5b3-dc4d-4d46-9832-78a247eba48a">

So we need a way to provide an alias to the registered class.

**Comment by Bromeon** [comment]
Suggested syntax:

```rs
#[derive(GodotClass)]
#[class(init, base=Node2D, rename=GodotName)]
struct RustName {
   ... 
}
```
Should also be documented in the [`GodotClass` derive macro](https://godot-rust.github.io/docs/gdext/master/godot/bind/derive.GodotClass.html).
