### ISSUE TITLE
Allow creating editor plugins

### ISSUE THREAD

**Issue by lilizoey** [godot-rust/gdext#333]
In 4.1 it is now possible for gdextension libraries to register editor plugins. https://github.com/godotengine/godot/pull/77010

It seems we just need to call `editor_add_plugin` to add a new plugin, and `editor_remove_plugin` to remove it. We should probably make the unregistering automatic by default. we can for instance add it in the default layer's deinit method. but we should make sure to document that if you override that function, you should either manually unregister editor plugins somewhere else, or re-add the automatic unregistration function.

**Comment by atty303** [comment]
EditorImportPlugin を Rust で書いているので、これが出来ると嬉しいです。

**Comment by Bromeon** [comment]
@atty303 could you elaborate your experience with it? Where would gdext come in handy?
