### ISSUE TITLE
Documentation for often-used APIs

### ISSUE THREAD

**Issue by Bromeon** [godot-rust/gdext#35]
Several APIs are currently undocumented. We should prioritize symbols which will definitely be manually maintained (e.g. geometric types in `godot::builtin` might get some docs from Godot later).

Examples:
* `godot::log`
* `godot::bind` -- maybe provide small usage examples of the proc-macros
* select types from `godot::builtin`
   * `Variant`
   * `Array`
   * `Dictionary`
   * `Signal`
   * `Callable`

**Comment by astrale-sharp** [comment]
I'm taking a look at this ;)
