### ISSUE TITLE
Exported `Option<Gd<Node2D>>` attribute cannot be cleared in Editor

### ISSUE THREAD

**Issue by B4rc1** [godot-rust/gdext#354]
I have this class
```rust
#[derive(GodotClass)]
#[class(init, base = TileMap)]
pub struct BoardManager {
    #[base]
    tile_map: Base<TileMap>,

    #[export]
    #[init]
    player_units: Option<Gd<Node2D>>,
}
```
Which as you can see exports a Node2D property `player_units`. It shows up as you would expect in the editor, can be assigned to a node and accessed in the code.

But when I try to press the "clear" button in godots editor:
![a](https://github.com/godot-rust/gdext/assets/10383737/a9e9e4ca-a797-45c1-9bdf-dbc35391756d)

The reference is not cleared and I get this error:
```
  /home/jonas/.cargo/git/checkouts/gdext-76630c89719e160c/fd1d50f/godot-core/src/lib.rs:133 - Rust function panicked in file /home/jonas/.cargo/git/checkouts/gdext-76630c89719e160c/fd1d50f/godot-core/src/builtin/meta/signature.rs at line 224. Context: set_player_units
  /home/jonas/.cargo/git/checkouts/gdext-76630c89719e160c/fd1d50f/godot-core/src/lib.rs:84 - Panic msg:  set_player_units: parameter [0] has type core::option::Option<godot_core::obj::gd::Gd<godot_core::gen::classes::node_2d::re_export::Node2D>>, which is unable to store argument Variant(ty=NodePath, val=)
```

**Comment by vortexofdoom** [comment]
I can't reproduce this on latest godot and gdext.

**Comment by Bromeon** [comment]
I _can_ reproduce it 😉 
You can test this in the example's `main_scene.rs`, by adding `#[export]` and then setting + clearing it in the editor:
```rs
    #[export]
    music: Option<Gd<AudioStreamPlayer>>,
```

It's interesting, the 🔁 reset button does reset it as expected.
However, the clear 🧹 one does not:

![Clearing Godot properties](https://github.com/godot-rust/gdext/assets/708488/a030a63b-6eef-4515-b084-aa703ddcdebe)

There is a panic happening on clear. I've found that there's a very subtle behavior: Godot sends an object null pointer inside the `Variant` (varcall) when pressing _reset_. However, when pressing clear, it sends a `NodePath` which is empty 🤔 I don't know why that happens, but I'll implement a workaround.
