### ISSUE TITLE
Ergonomics: ArrayType

### ISSUE THREAD

**Issue by jcdickinson** [godot-rust/gdext#366]
I'm currently messing around with mesh procedural generation, and I've ported the Godot `ArrayMesh` tutorial to rust. `ArrayType` currently has pretty bad ergonomics:

```rust
surface_array.resize(ArrayType::ARRAY_MAX.ord() as usize);
surface_array.set(ArrayType::ARRAY_VERTEX.ord() as usize, verts.to_variant());
surface_array.set(ArrayType::ARRAY_TEX_UV.ord() as usize, uvs.to_variant());
surface_array.set(ArrayType::ARRAY_NORMAL.ord() as usize, normals.to_variant());
surface_array.set(ArrayType::ARRAY_INDEX.ord() as usize, indices.to_variant());
```

I think this would be ideally be instead exposed as an enum with `Into<usize>`. It currently looks like this type is used nowhere, so it could be changed. I'm open to contributing a fix, if the maintainers could provide some direction on how they want this solved.

Here's the entire lib, in the event that someone is searching how to do this from gdext:

```rust
use godot::{
    engine::{
        mesh::{ArrayType, PrimitiveType},
        ArrayMesh, Mesh, MeshInstance3D, MeshInstance3DVirtual,
    },
    prelude::*,
};

struct MyExtension;

#[gdextension]
unsafe impl ExtensionLibrary for MyExtension {}

#[derive(GodotClass)]
#[class(base=MeshInstance3D)]
struct Boxels {
    #[base]
    instance: Base<MeshInstance3D>,
}

#[godot_api]
impl MeshInstance3DVirtual for Boxels {
    fn init(instance: Base<MeshInstance3D>) -> Self {
        godot_print!("Hello, world!"); // Prints to the Godot console

        Self { instance }
    }

    fn ready(&mut self) {
        let mut verts = PackedVector3Array::new();
        let mut uvs = PackedVector2Array::new();
        let mut normals = PackedVector3Array::new();
        let mut indices = PackedInt32Array::new();

        verts.push(Vector3::new(0.0, 0.0, 0.0));
        verts.push(Vector3::new(1.0, 0.0, 0.0));
        verts.push(Vector3::new(0.0, 1.0, 0.0));
        verts.push(Vector3::new(1.0, 1.0, 0.0));

        uvs.push(Vector2::new(0.0, 0.0));
        uvs.push(Vector2::new(1.0, 0.0));
        uvs.push(Vector2::new(0.0, 1.0));
        uvs.push(Vector2::new(1.0, 1.0));

        normals.push(Vector3::new(0.0, 0.0, -1.0));
        normals.push(Vector3::new(0.0, 0.0, -1.0));
        normals.push(Vector3::new(0.0, 0.0, -1.0));
        normals.push(Vector3::new(0.0, 0.0, -1.0));

        indices.push(0);
        indices.push(1);
        indices.push(3);
        indices.push(0);
        indices.push(3);
        indices.push(2);

        let mut surface_array = VariantArray::new();
        surface_array.resize(ArrayType::ARRAY_MAX.ord() as usize);
        surface_array.set(ArrayType::ARRAY_VERTEX.ord() as usize, verts.to_variant());
        surface_array.set(ArrayType::ARRAY_TEX_UV.ord() as usize, uvs.to_variant());
        surface_array.set(ArrayType::ARRAY_NORMAL.ord() as usize, normals.to_variant());
        surface_array.set(ArrayType::ARRAY_INDEX.ord() as usize, indices.to_variant());

        let mut mesh = ArrayMesh::new();
        mesh.add_surface_from_arrays(PrimitiveType::PRIMITIVE_TRIANGLES, surface_array);

        self.instance.set_mesh(mesh.upcast::<Mesh>());
    }
}
```

*aside: I'm amazed at how effortless using this was. kudos!*

**Comment by Bromeon** [comment]
> I think this would be ideally be instead exposed as an enum with `Into<usize>`.

The Rust `enum` requires that all constants have different ordinals/discriminants. Godot doesn't guarantee this, sometimes multiple enum variants have the same value, e.g. when renaming/deprecating them. So we have to use `const` instead.

---

> It currently looks like this type is used nowhere, so it could be changed.

[`ArrayType`](https://godot-rust.github.io/docs/gdext/master/godot/engine/mesh/struct.ArrayType.html) is part of generated code. So whatever we do will apply to all engine enums, and we cannot look at this type in isolation.

---

> ArrayType currently has pretty bad ergonomics:
> ```rs
> let mut surface_array = VariantArray::new();
> surface_array.resize(ArrayType::ARRAY_MAX.ord() as usize);
> surface_array.set(ArrayType::ARRAY_VERTEX.ord() as usize, verts.to_variant());
> surface_array.set(ArrayType::ARRAY_TEX_UV.ord() as usize, uvs.to_variant());
> ...
> ```

The main issue seems to be the `as usize`, right?

I'm not sure if `Into` is a good choice here, as I'd like to avoid implicit conversions from enums to integers (through `impl Into<usize>` parameters), and because it may be worse for type inference (e.g. in `let index = my_enum.into()`). 

What if we could do this instead?
```cpp
surface_array.resize(ArrayType::ARRAY_MAX.to_usize());
surface_array.set(ArrayType::ARRAY_VERTEX.to_usize(), verts.to_variant());
surface_array.set(ArrayType::ARRAY_TEX_UV.to_usize(), uvs.to_variant());
...
```
We could only provide `to_usize()` for enums where every ordinal is non-negative, but this is possible to achieve in codegen.

**Comment by jcdickinson** [comment]
I gave this more thought, and maybe a `godot-contrib` (or similar) crate could work in this case: somewhere to smooth over any extremely common patterns or warts. We could have something like:

```rust
#[repr(transparent)]
pub struct SurfaceArray {
   array: VariantArray
}

impl SurfaceArray {
   pub fn get_vertices(&self) -> Option<PackedVector3Array>;
   pub fn set_vertices(&mut self, arr: PackedVector3Array);
   pub fn vertices(&mut self) -> PackedVector3Array; // Get or create
   // etc.
}

impl Into<VariantArray> for SurfaceArray;
impl Into<SurfaceArray> for VariantArray;
```

> We cannot provide to_usize() for all enums though. Maybe some criteria could be:

I'll poke around at this and see how it goes, `impl Into<usize>` might be a good start.

**Comment by Bromeon** [comment]
> I gave this more thought, and maybe a `godot-contrib` (or similar) crate could work in this case: somewhere to smooth over any extremely common patterns or warts.

Interesting idea 🤔 maybe we can collect such high-level patterns somewhere? Then depending on the use cases, we could determine if they are in scope for gdext or not... I'll open an issue to track this.
