### ISSUE TITLE
itest doesn't say which test failed 

### ISSUE THREAD

**Issue by lilizoey** [godot-rust/gdext#388]
i just ran itest and got this:
```
...
Test result: FAILED. 419 passed; 1 failed, 5 skipped.
  Time: 0.15s.  (Rust 0.13s, GDScript 0.01s)

=====================
gdext: checks FAILED.
=====================
```
so now i have to scan through all tests to find which one failed. it would be much nicer if it just says which tests failed right here near the end.

**Comment by Bromeon** [comment]
I implemented this a while ago.
