### ISSUE TITLE
Expose variable to the editor

### ISSUE THREAD

**Issue by vars1ty** [godot-rust/gdext#397]
I'm new to Godot and GDExt as a whole, so apologies if this has already been answered.
I read through the documentation and noticed that `#[property]` was a thing in Godot 3.0 until the 3-series ended.
Is there any way of replicating this using Godot 4 and GDExt? As the only workaround I have currently found, is to use metadata, which doesn't get found in `init`, but rather `ready`.

**Comment by Bromeon** [comment]
Hey yes, you can use `#[var]` and `#[export]`.

They are documented in [`#[derive(GodotClass)]`](https://godot-rust.github.io/docs/gdext/master/godot/bind/derive.GodotClass.html#properties-and-exports) 🙂

**Comment by vars1ty** [comment]
Thanks! Didn't find that page when I was searching around, will pin it in my browser from now on 👍🏽
