### ISSUE TITLE
Virtual function calls panic with `not implemented` if they are conditionally excluded from compilation

### ISSUE THREAD

**Issue by jrockett6** [godot-rust/gdext#399]
E.g. this will panic with `'not implemented'` if the "client" feature is not included.

```rust
#[godot_api]
impl CharacterBody3DVirtual for MyCharacter {
    #[cfg(feature = "client")]
    fn ready(&mut self) {
             // Do stuff
    }
}
```

This is not a huge deal if there isn't any overhead from including the attribute inside the function body - but I'm not familiar with this, e.g. 

```rust
#[godot_api]
impl CharacterBody3DVirtual for MyCharacter {
    fn process(&mut self, delta: f64) {
             #[cfg(feature = "client")]
             {
                  // Do our client only stuff
             }

             // Is there overhead here from calling into an empty process block for potentially every character that is not part of client?
    }
}
```

**Comment by Bromeon** [comment]
This looks a bit like a special-case of https://github.com/godot-rust/gdext/issues/379 🤔

**Comment by jrockett6** [comment]
Just another motivating case for this. There can be only a single `{Node}Virtual` impl, as such it is nice to conditionally compile certain `#[func]`s that are e.g. only on the client/server in my case. However if these call any other client-specific functions then compilation fails (because the #[func] is not actually conditionally excluded). 

E.g.

```rust
    #[cfg(feature = "client")]
    #[func]
    fn handle_client_input_stuff(&mut self, arg: Variant, ) {
         // calls to client-only fn's will cause non-client compilations to fail
    }
```

**Comment by PgBiel** [comment]
If this helps, I noticed that `cfg` will also cause problems in other places, e.g. 

```rust
#[godot_api]
impl Main {
    #[cfg(feature = "no")]
    #[func]
    fn game_over(&mut self) {
```

results in the error (seemingly from the codegen result):
![image](https://github.com/godot-rust/gdext/assets/9021226/645c164c-8d54-4ff3-bde8-933b7fef3741)

...but changing the order of the attribute macros seems to make it work fine (the function isn't even picked up by `#[func]`):
```rust
#[godot_api]
impl Main {
    #[func]
    #[cfg(feature = "no")]
    fn game_over(&mut self) {
```

Perhaps a possible solution could be special-cased for `cfg`, such that it would be applied to the generated FFI code block as well? For other attribute macros, one could, with some degree of certainty, assume that they won't modify the function's name or make it disappear, as is somewhat done today; however, there should certainly be some sort of "escape hatch" to ensure that a given attribute macro would be applied to both the original function impl and its generated FFI block, e.g. through something like (note: prone to bikeshedding etc.)

```rust
#[godot_api]
impl Main {
    #[func(
      cond_attrs = (cfg(feature = "no"), something(else), ...)
    )] // #[cfg(...)] could definitely be special-cased and supported though
    fn game_over(&mut self) {
```
