### ISSUE TITLE
Equivalent for `await $SomeTimer.timeout`?

### ISSUE THREAD

**Issue by WHMHammer** [godot-rust/gdext#432]
I am following the Godot "Your first 2D game" [tutorial](https://docs.godotengine.org/en/stable/getting_started/first_2d_game/06.heads_up_display.html). Part of the logic is to wait for a timer to timeout to proceed to the next step. Below are the GDScript codes:

```
func show_game_over():
    show_message("Game Over")
    # Wait until the MessageTimer has counted down.
    await $MessageTimer.timeout

    $Message.text = "Dodge the\nCreeps!"
    $Message.show()
    # Make a one-shot timer and wait for it to finish.
    await get_tree().create_timer(1.0).timeout
    $StartButton.show()
```

However, I did not find any equivalent function in the godot-rust `Timer` [documentation](https://godot-rust.github.io/docs/gdext/master/godot/engine/struct.Timer.html). I also checked the [example codes](https://github.com/godot-rust/gdext/blob/master/examples/dodge-the-creeps/rust/src/hud.rs#L26-L35) in this repo, which does not have this wait for timeout logic at all. The same issue exists on [`SceneTreeTimer`](https://godot-rust.github.io/docs/gdext/master/godot/engine/struct.SceneTreeTimer.html).

What are the equivalents for `await $SomeTimer.timeout` in godot-rust? Thanks!

**Comment by Bromeon** [comment]
This is not possible at the moment. It would need async support, which is unfortunately quite a pain in Rust.

gdnative supports it though, it looks like this:
https://godot-rust.github.io/book/gdnative/recipes/async-tokio.html

So maybe we can reuse prior art here, but it's not a priority at the moment.

**Comment by jrockett6** [comment]
@WHMHammer If you don't mind defining an extra `#[func]` that handles the `await`ed logic you can do this as a workaround:
```rust
let mut timer = self.base.get_tree().unwrap().create_timer(1.0).unwrap();
timer.connect("timeout".into(), self.base.callable("awaited_func"));
```

**Comment by Bromeon** [comment]
@jrockett6 that's actually a great idea. And in other news, I added [`Callable::from_fn()`](https://github.com/godot-rust/gdext/pull/418) a few weeks ago, so you don't even need a `#[func]` but could technically pass any closure. 

It's a bit more manual at the moment (you only get a variant slice), so `#[func]` might be easier, but eventually `from_fn()` should also support such signatures.

**Comment by WHMHammer** [comment]
@jrockett6 @Bromeon  I created additional Timers in Godot editor and set their timeout handlers to the logics after the delays. Thank you for your alternative solutions though!

**Comment by musjj** [comment]
Shouldn't this stay open until we have proper async support?

**Comment by Bromeon** [comment]
@musjj There's https://github.com/godot-rust/gdext/issues/640 as well. But we haven't decided yet if we want to implement it.
