### ISSUE TITLE
Hot reload final steps

### ISSUE THREAD

**Issue by kkolyan** [godot-rust/gdext#434]
I just checked hot reload with Godot and gdext latest master branches and instead of loading new class, I have a `Extension marked as reloadable, but attempted to register class 'SuperPlayer' which doesn't support reloading. Perhaps your language binding don't support it? Reloading disabled for this extension.`

The place where error generated:
https://github.com/godotengine/godot/blob/4c3dc26367518e006f8555c12f5d2df0b8a28192/core/extension/gdextension.cpp#L431

Seems like we need to supply `recreate_instance_func`. Also, seems like that requires migration from deprecated `_register_extension_class` to `_register_extension_class2`.

Steps to reproduce a problem:
1. get Godot sources and build them. I use `scons dev_build=yes debug_symbols=yes platform=windows compiledb=yes -j8` for debugging from CLion.
2. set GODOT4_BIN to the path of result executable
3. select some working gdext project (dodge-the-creeps from examples is ok) 
4. add `reloadable = true` to the `configuration` section of `.gdextension` file
5. comment out some class
6. run `cargo build --package dodge-the-creeps--lib --features custom-godot`
7. run Godot executable with `--editor --path <path to dodge-the-creeps Godot folder>`, wait it for loading scene
8. run `cargo build --package dodge-the-creeps--lib --features custom-godot` again
9. switch back to Godot editor and see error in console.

**Comment by Bromeon** [comment]
Yes, it's simply not implemented yet.

The equivalent for godot-cpp: https://github.com/godotengine/godot-cpp/pull/1200
