### ISSUE TITLE
Missing IDE Support with RustRover or CLion + Rust plugin

### ISSUE THREAD

**Issue by NicolasVidal** [godot-rust/gdext#435]
Hello, I'm quite new to the Godot community and I try to use Rust in Godot.
I noticed (it's also true with GDNative) that RustRover or Rust plugin in Clion don't seem to recognize Godot structs.

For instance, if I follow the tutorial :
![image](https://github.com/godot-rust/gdext/assets/5675478/6c577979-5a72-4ae8-8d3b-40c85646f3be)

Thus, I have no completion or help in the IDE regarding Godot types which is a bit annoying.
I was wondering if I was missing a configuration step or anything else.

This is not a blocking issue as I can compile and test in Godot the rotating sprite with success, but it would be quite convenient if the IDE was playing nice with the godot crate.

Thank you for your future answers and for your awesome work.

Cheers.

Nicolas.

**Comment by Bromeon** [comment]
I'm using CLion for everyday development and don't have this issue. Did it occur with CLion or just the experimental RustRover?

Can you try refreshing the Cargo menu on the right of your IDE?

![Cargo menu](https://github.com/godot-rust/gdext/assets/708488/697b4096-6a6b-4490-9154-67ccc2380d3a)

**Comment by NicolasVidal** [comment]
Hello @Bromeon,
Thank you for your quick reply.

Indeed it is the case in RustRover and CLion + Rust plugin.

Reloading the cargo project in the tool window did the trick for gdext, but not for my other project in gdnative. 

Maybe I should move this issue in GDNative then ?

Thank you again for you quick reply.

**Comment by NicolasVidal** [comment]
ok I found the issue already opened in gdnative repo, closing this one.
