### ISSUE TITLE
`onready` attribute when deriving `GodotClass` [feature request]

### ISSUE THREAD

**Issue by speelbarrow** [godot-rust/gdext#447]
Hey folks!

GDScript has an [`onready` annotation](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#onready-annotation) you can apply when declaring a variable that allows you to define how the value should be initialized **when [`_ready`](https://docs.godotengine.org/en/4.1/classes/class_node.html#class-node-method-ready) is called** (as opposed to `init`). In this library, when using the [derive macro for `GodotClass`](https://godot-rust.github.io/docs/gdext/master/godot/bind/derive.GodotClass.html), the attribute `#[init(default = ... )]` can be used to set a default value for the `struct` field it tags. Would it be possible to add something like `#[init(onready = ...)]` for object initialization at `ready` time? Based on how this library currently works, this would require the tagged field to be `Option<T>` (so that at `init` time the field can be initialized in some way). Maybe the attribute could apply that `Option` wrapper itself?

I'm not super familiar with the internals of this library (yet), so I'm not entirely sure if this is even possible/how exactly one would go about implementing it. However, it is a feature I'd love to see implemented!

Thanks for taking the time to read this :)

**Comment by Bromeon** [comment]
Please check for existing issues: https://github.com/godot-rust/gdext/issues/130
But you remind me of some experiments I started a while ago, will answer there.
