### ISSUE TITLE
ImmediateMesh crash

### ISSUE THREAD

**Issue by CodedNil** [godot-rust/gdext#455]
I can't seem to get ImmediateMesh working, it always crashes on surface_begin as soon as godot launches

```rust
#[godot_api]
impl RigidBody3DVirtual for Entity {
    fn init(base: Base<RigidBody3D>) -> Self {
        let mut instance = Self { base };

        // Add render mesh to it
        let mut render_mesh = MeshInstance3D::new_alloc();
        let mut render_geometry = ImmediateMesh::new();
        render_mesh.set_mesh(render_geometry.upcast::<Mesh>());
        instance.base.add_child(render_mesh.upcast::<Node>());

        instance
    }

    fn process(&mut self, delta: f64) {
        if let Some(render_mesh_node) = self.base.get_child(0) {
            if let Some(render_mesh) = render_mesh_node.try_cast::<MeshInstance3D>() {
                if let Some(render_geometry) = render_mesh.get_mesh() {
                    let mut render_geometry = render_geometry.cast::<ImmediateMesh>();
                    render_geometry.clear_surfaces();
                    render_geometry.surface_begin(PrimitiveType::PRIMITIVE_TRIANGLES);  // Always seems to crash at this point
                    render_geometry.surface_add_vertex(Vector3::LEFT);
                    render_geometry.surface_add_vertex(Vector3::FORWARD);
                    render_geometry.surface_add_vertex(Vector3::ZERO);
                    render_geometry.surface_end();
                }
            }
        }
    }
}
```

**Comment by Bromeon** [comment]
Can you give some context?

What does crash mean, panic or UB? Is there an error message on the console?

**Comment by CodedNil** [comment]
thread '<unnamed>' panicked at 'not implemented: see #156', C:\Users\coded\.cargo\git\checkouts\gdext-76630c89719e160c\1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Not sure what this means in reference to issue #156 or how to go about addressing it, this code looks correct according to all the documentation.

**Comment by Bromeon** [comment]
Ah yes, this is indeed the bug mentioned in issue #156. 

`surface_begin()` internally calls [`surface_begin_ex()`](https://godot-rust.github.io/docs/gdext/master/godot/engine/struct.ImmediateMesh.html#method.surface_begin_ex), which has an optional parameter `material`. If that one is not provided, the call currently fails.

So we need to fix that; as a workaround you could try:
```rs
render_geometry.call("surface_begin", &[]);
```

**Comment by CodedNil** [comment]
Brilliant, this works

```rust
render_geometry.call(
    StringName::from("surface_begin"),
    &[
        Variant::from(PrimitiveType::PRIMITIVE_TRIANGLES),
        Variant::from(material.clone()),
    ],
);
```

Thanks for your help

**Comment by Bromeon** [comment]
If you _do_ have a material, this should also work:
```rs
render_geometry.surface_begin_ex(PrimitiveType::PRIMITIVE_TRIANGLES)
    .material(material.clone())
    .done();
```
The problem appears if you _don't_ specify the material.
