### ISSUE TITLE
`var` properties without `export` are still saved to the scene file

### ISSUE THREAD

**Issue by HenryWConklin** [godot-rust/gdext#463]
## Issue

Fields marked with `#[var]` are written to scene files (and presumably resource files) even without also adding `#[export]`

## Expected behavior

`#[var]` fields should be accessible as properties, but not saved. Similar to the behavior in GDScript. 

## Repro

[var-persisted-repro.zip](https://github.com/godot-rust/gdext/files/13137197/var-persisted-repro.zip)

1. `cargo build`
2. Open `scene.tscn` in the editor, save the scene
3. Inspect `scene.tscn` and note that `var` is included as a property of the `ExampleNode`

**Comment by lilizoey** [comment]
according to the [documentation of godot](https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#enum-globalscope-propertyusageflags), script variables should also be serialized and saved to file. so unless these docs sre wrong then this is also how gdscript works.

**Comment by HenryWConklin** [comment]
So, testing with a script on a node:

```
@tool
extends Node

var test: int = 0

@export
var test2: int = 0


func _process(_delta):
	test2 += 1
	test += 1
```

Have to do a bit of gymnastics to get the value to change in the editor so it actually gets saved. 

Gives this in the scene file:

```
[node name="Node" type="Node" parent="ExampleNode"]
script = ExtResource("1_2vnkk")
test2 = 78
```

And here's the `get_property_list` with the usage flags:

```
{ "name": "test", "class_name": &"", "type": 2, "hint": 0, "hint_string": "", "usage": 4096 }
{ "name": "test2", "class_name": &"", "type": 2, "hint": 0, "hint_string": "int", "usage": 4102 }, 
```
So `var` is just `PROPERTY_USAGE_SCRIPT_VARIABLE` 
and `@export var` is `PROPERTY_USAGE_SCRIPT_VARIABLE | PROPERTY_USAGE_DEFAULT`

So maybe the docs are wrong/out of date? I'm not too sure what `PROPERTY_USAGE_SCRIPT_VARIABLE` is doing but it doesn't seem to actually serialize things. There's also `PROPERTY_USAGE_STORAGE` for that

**Comment by Bromeon** [comment]
As mentioned by @lilizoey, this would be against Godot's specification. We should check that Godot works correctly before trying to workaround the problem in godot-rust.

Thanks for testing it in GDScript. Which version of Godot did you use? (`godot4 --version`)

**Comment by HenryWConklin** [comment]
Version is `v4.1.2.stable.official [399c9dc39]`

Agree it's worth clarifying, but from my understanding the purpose of `export` is to mark that the variable should be serialized. Some quotes from the docs:

[Intro to exports](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_exports.html#introduction-to-exports)
> In Godot, class members can be exported. This means their value gets saved along with the resource (such as the [scene](https://docs.godotengine.org/en/stable/classes/class_packedscene.html#class-packedscene)) they're attached to. They will also be available for editing in the property editor. Exporting is done by using the `@export` annotation.

[Reference for the `@export` annotaiton](https://docs.godotengine.org/en/stable/classes/class_%40gdscript.html#annotations)

> `@export ( )`
>
> Mark the following property as exported (editable in the Inspector dock and saved to disk). ...

So I feel like the actual behavior and the intent expressed in the gdscript docs contradict what these flag descriptions say.

Easy to work around either way, but seemed off to me so thought I'd report it.

**Comment by lilizoey** [comment]
I'd recommend filing an issue with godot itself to see what they think. It may just be a documentation bug. Because yeah those docs seem to cnotradict themself.
