### ISSUE TITLE
Trying to extend a TileMap but functions are inconsistent with GODOT API or missing documentation

### ISSUE THREAD

**Issue by jgunzelman88** [godot-rust/gdext#468]
I'm trying to set the cells in a 2d TileMap.  But the set_cell function only take 2 arguments the coordinates Vector and the layer.  How am I suppose to map which tile to use?  That is a 3rd argument in GDScript. But is missing here.

**Comment by PgBiel** [comment]
You might be looking for `set_cell_ex`: https://godot-rust.github.io/docs/gdext/master/godot/engine/struct.TileMap.html#method.set_cell_ex

**Comment by jgunzelman88** [comment]
That makes sense thank you!!
For anyone viewing this in the furture:
```rust                
let coords = Vector2i {
      x: x_map as i32,
      y: y_map as i32,
};
let cell = map.set_cell_ex(0, coords);
let atlas = Vector2i {
    x: 0,
    y: 0
};
cell.atlas_coords(atlas).source_id(0).done();
```

**Comment by Bromeon** [comment]
I was first thinking that adding a link to the `_ex` method in the base method could be an idea. But in docs they're anyway next to each other, and many people don't even check docs. Maybe for inline IDE docs though? 🤔

**Comment by PgBiel** [comment]
> Maybe for inline IDE docs though? 🤔

Sounds like a good reason to me
