### ISSUE TITLE
build fails in macos due to `failed to resolve: could not find open_xr_action in engine`

### ISSUE THREAD

**Issue by kuruk-mm** [godot-rust/gdext#474]
I updated from 4.1.1 to 4.1.3, and gdext from `00ba8c9d` to `02f4acf5` and I started getting the following error in MacOS (Windows and Linux are OK):

```
error[E0433]: failed to resolve: could not find `open_xr_action` in `engine`
  --> /Users/mateomiccino/.cargo/git/checkouts/gdext-76630c89719e160c/02f4acf/godot-core/src/gen/classes/open_xr_interaction_profile_metadata.rs:88:223
   |
88 | ...dotString, action_type: crate::engine::open_xr_action::ActionType,) {
   |                                           ^^^^^^^^^^^^^^ could not find `open_xr_action` in `engine`

error[E0433]: failed to resolve: could not find `open_xr_action` in `engine`
  --> /Users/mateomiccino/.cargo/git/checkouts/gdext-76630c89719e160c/02f4acf/godot-core/src/gen/classes/open_xr_interaction_profile_metadata.rs:90:113
   |
90 |             type CallSig = ((), GodotString, GodotString, GodotString, GodotString, GodotString, crate::engine::open_xr_action::ActionType);
   |                                                                                                                 ^^^^^^^^^^^^^^ could not find `open_xr_action` in `engine`
```

I compared the generated files (at .cargo/git/checkouts/gdext-76630c89719e160c/02f4acf/godot-core/src/gen/classes) between Linux and Mac, and Mac is not generating the `open_xr_**` files, it just generating the `open_xr_interaction_profile_metadata`.

More details in a GH Action:
https://github.com/decentraland/godot-explorer/actions/runs/6824669204/job/18561040610

I'm using pre-build
```
[patch."https://github.com/godot-rust/godot4-prebuilt".godot4-prebuilt]
git = "https://github.com//godot-rust/godot4-prebuilt"
branch = "4.1.3"
```
entire cargo.toml: https://github.com/decentraland/godot-explorer/blob/main/rust/decentraland-godot-lib/Cargo.toml

**Comment by Bromeon** [comment]
These are not supported by Godot 4.1 in macOS, their exclusion is thus intentional.
For 4.2 builds (including `custom-godot` ones against dev), they are available.

See https://github.com/godot-rust/gdext/pull/405.

**Comment by Bromeon** [comment]
Wait, I just saw that your error mentions `open_xr_interaction_profile_metadata` -- this one is not in the list. Maybe we need to use `OpenXR` prefixes instead of hardcoding all concrete classes.

**Comment by kuruk-mm** [comment]
> These are not supported by Godot 4.1 in macOS, their exclusion is thus intentional. For 4.2 builds (including `custom-godot` ones against dev), they are available.
> 
> See #405.

I'm not using those. I'm just trying to fix the error that was blocking me.

I removed this in my Cargo.toml
```
[patch."https://github.com/godot-rust/godot4-prebuilt".godot4-prebuilt]
git = "https://github.com//godot-rust/godot4-prebuilt"
branch = "4.1.3"
```

and it started working. I don't understand well how the prebuild artifact works.

**Comment by Bromeon** [comment]
Yep, see my last comment. https://github.com/godot-rust/gdext/pull/475 should fix this, could you check?
