### ISSUE TITLE
JoyButton can not support larger than 21 buttons

### ISSUE THREAD

**Issue by hanya** [godot-rust/gdext#479]
Gamepad can have many buttons and some controller has 24 buttons.
JoyButton enum defines the largest value as JOY_BUTTON_SDL_MAX(21) except JOY_BUTTON_MAX(128).
``try_from_ord`` function checks the value of passed enum value and returns None for out of definition of enums.

**Comment by Bromeon** [comment]
Hello 🙂 

This repo is about the Rust bindings of Godot. What you describe about [`JoyButton`](https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#enumerations) seems like a limitation in Godot itself and should thus be reported upstream, in https://github.com/godotengine/godot/issues. 

Maybe check first if there is no similar issue already, or try to understand why the limit is 21 buttons.
