### ISSUE TITLE
Few `godot::engine` types seem missing

### ISSUE THREAD

**Issue by mhgolkar** [godot-rust/gdext#485]
Few `godot::engine` types (nodes/structs), including but not limited to `TextureRect`, `GraphEdit`, `GraphNode`, `NavigationMesh`, etc. seem to being disappeared.
I faced this after trying to migrate from [`0d4670f`] to [`46f94f6`] (latest at the time).
Missing structs seem to be matching in  [`is_class_experimental`] function of `godot-codegen/src/special_cases.rs`; so there might be a relation. I haven't investigated it further though.

[`is_class_experimental`]: https://github.com/godot-rust/gdext/blob/6ae357a4b4bc93e2ad1438c6489b05ecd9f7dd84/godot-codegen/src/special_cases.rs
[`0d4670f`]: https://github.com/godot-rust/gdext/commit/0d4670fac4d83a3e690a605c3fbbee4b115cadce
[`46f94f6`]: https://github.com/godot-rust/gdext/commit/46f94f6387b1054cae3fa82da7e4981083cdd866

**Comment by Bromeon** [comment]
This is by design, they are feature-gated due to no stability from Godot side.
Please check [the docs](https://godot-rust.github.io/docs/gdext/master/godot/#cargo-features):

> ## Cargo features
> 
> * `experimental-godot-api`
>   Access to godot::engine APIs that Godot marks “experimental”. These are under heavy development and may change at any time. If you opt in to this feature, expect breaking changes at compile and runtime.

**Comment by mhgolkar** [comment]
Oh! So I was *missing* that!
Thanks.
