### ISSUE TITLE
Reload Current Project (Help Needed)

### ISSUE THREAD

**Issue by ulvido** [godot-rust/gdext#488]
I made a godot plugin for rust builds. But stuck at the `Reload Current Project` part. Is there a way to reload godot project programatically or see the changes without reloading? Thank you.

![Peek 2023-11-19 15-18](https://github.com/godot-rust/gdext/assets/27722274/b3d433ee-dcd7-4344-85d9-4e03e833a968)

**Comment by TCROC** [comment]
> I made a godot plugin for rust builds. But stuck at the `Reload Current Project` part. Is there a way to reload godot project programatically or see the changes without reloading? Thank you.
> 
> ![Peek 2023-11-19 15-18](https://user-images.githubusercontent.com/27722274/284056915-b3d433ee-dcd7-4344-85d9-4e03e833a968.gif) [ ![Peek 2023-11-19 15-18](https://user-images.githubusercontent.com/27722274/284056915-b3d433ee-dcd7-4344-85d9-4e03e833a968.gif) ](https://user-images.githubusercontent.com/27722274/284056915-b3d433ee-dcd7-4344-85d9-4e03e833a968.gif) [ ](https://user-images.githubusercontent.com/27722274/284056915-b3d433ee-dcd7-4344-85d9-4e03e833a968.gif)

Yes, add the ``reloadable=true`` to your ``.gdextension`` file.  Here is mine for example:

```
[configuration]
entry_symbol = "gdext_rust_init"
compatibility_minimum = 4.2
reloadable = true

[libraries]
linux.debug.x86_64="res://src/rust/lib/target/debug/librust.so"
linux.release.x86_64="res://src/rust/lib/target/release/librust.so"
windows.debug.x86_64="res://src/rust/lib/target/debug/rust.dll"
windows.release.x86_64="res://src/rust/lib/target/release/rust.dll"
```

**Comment by TCROC** [comment]
Note: I believe you have to be using godot 4.2

**Comment by ulvido** [comment]
Oh thank you, great news. I am using stable steam version which is 4.1.3 but definitely try it. 
For clarityhow to use, so if we write `reloadable=true` , godot will track if the lib files rebuilded and refresh editor automaticaly, am I right? No need to script anything beyond `reloadable=true`

**Comment by TCROC** [comment]
That has been my experience so far.  And it appears to be a hot reload to, so the entire editor doesn't reload.  Just the gdextension and editor panels for properties refresh.

From the user / dev perspective, its identical to modifying a gdscript other than the fact that you have to run "cargo build".  But once that is run, the editor refreshes :)

Idk if they are planning to backport this feature to Godot 4.1.  I'm personally building from source and syncing with godot master a few times a week and can confirm it works in Godot master / 4.2

**Comment by ulvido** [comment]
Thank you 🙏🏻 Very very appreciated
