### ISSUE TITLE
GFile::read is slow

### ISSUE THREAD

**Issue by andreymal** [godot-rust/gdext#513]
I noticed that reading a ~8MB file (with dozens of seeks if it's important) takes about half a second (and even longer in a debug build).

I rewrote it to use `get_buffer` instead of `get_u8` and got a ~70x speedup at the cost of slightly increased heap usage (but I'm not sure if this implementation is correct):

```rust
impl Read for GFile {
    fn read(&mut self, buf: &mut [u8]) -> IoResult<usize> {
        let mut read_bytes = 0;
        let mut remaining_buf = buf;
        while !remaining_buf.is_empty() {
            let data = self.fa.get_buffer(
                std::cmp::min(remaining_buf.len(), Self::BUFFER_SIZE) as i64
            );
            // EOF is not an error in this specific case
            if self.fa.get_error() != Error::ERR_FILE_EOF {
                self.check_error()?;
            }
            if data.is_empty() {
                break;
            }
            remaining_buf[..data.len()].copy_from_slice(data.as_slice());
            remaining_buf = &mut remaining_buf[data.len()..];
            read_bytes += data.len();
        }

        Ok(read_bytes)
    }
}
```

**Comment by andreymal** [comment]
(A similar rewrite could also be applied to `GFile::write` but I'm too lazy to check it out)

**Comment by StatisMike** [comment]
@andreymal, this looks fantastic to me! I recommend incorporating tests and benchmarks into the `itest/rust` crate :)

In my previous experience with the `GFile` implementation, _I think_ that I encountered an issue where `fa.get_buffer` caused the `FileAccess` cursor to extend beyond the file contents, causing error. If this was really the case it should be seen with output of `itest` :)
I
