### ISSUE TITLE
Can `StringName` literals be optimized?

### ISSUE THREAD

**Issue by Des-Nerger** [godot-rust/gdext#531]
If I've understood it correctly, constructing a `StringName` once and then doing `.clone()` of it is non-negligibly more efficient than constructing it of `&str` from scratch every time we need a `StringName` to pass to the Godot API. So, naturally, `.clone()` should be used quite often:
```rust
  fn init(base: Base<Self::Base>) -> Self {
    Self {
      velocity: Vector2::ZERO,
      input: Input::singleton(),
      ui_left: "ui_left".into(),
      ui_right: "ui_right".into(),
      ui_up: "ui_up".into(),
      ui_down: "ui_down".into(),
      base,
    }
  }

  fn process(&mut self, delta: f64) {
    let o /*bject */ = self;
    o.velocity =
      o.input.get_vector(o.ui_left.clone(), o.ui_right.clone(), o.ui_up.clone(), o.ui_down.clone());
    ...
  }
```
So, why not do `#[derive(Copy)]` on `StringName` to make it less hairy?

**Comment by Bromeon** [comment]
> If I've understood it correctly, constructing a `StringName` once and then doing `.clone()` of it is non-negligibly more efficient than constructing it of `&str` from scratch

This would by the way be something interesting to measure. I specifically added support for direct construction in https://github.com/godotengine/godot/pull/78580, but it currently still needs to go through `String` due to UTF-8 validation.

If we don't validate for UTF-8, I could imagine we could use the [`StringName(const char* p_name, bool is_static)` constructor](https://github.com/godotengine/godot/blob/master/core/string/string_name.cpp#L210-L210) directly. There's still some work to be done, but it would likely level the playing field quite a bit.

**Comment by Des-Nerger** [comment]
> fear-of-missing-out

If you didn't impl From<&'static str> for StringName, it would ease the fear, I think.

**Comment by Bromeon** [comment]
> If you didn't impl From<&'static str> for StringName, it would ease the fear, I think.

I was actually considering this; but I'm not sure if it's worth the ergonomic penalty.

This is not just about literals but also conversions from pre-existing string slices; although I guess we could use an explicit constructor for those.

**Comment by lilizoey** [comment]
Couldn't we have [`from_latin1_with_nul`](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.StringName.html#method.from_latin1_with_nul) accept a [`CStr`](https://doc.rust-lang.org/std/ffi/struct.CStr.html#), then with rust 1.76 (to be released in early february) people can just use c string literals to initialize this?

**Comment by lilizoey** [comment]
with #652 merged, you can now efficiently construct `StringName`s using `c"some string".into()` or `StringName::from(c"some string")`. this should be faster than even cloning a `StringName`, though this isn't benchmarked.

I believe this should be a sufficiently good solution to this issue. If you need the performance you can simply replace usage of string literals with c-string liteeals and thus avoid utf-8 parsing entirely as well as any reference counting. And im skeptical this could be optimized much more than that.

So ill close this. if there is a concrete use-case for optimizing `StringName` literals further than this that isn't covered by this then feel free to re-open.
