### ISSUE TITLE
Could GODOT4_BIN be a relative path?

### ISSUE THREAD

**Issue by StagnationPoint** [godot-rust/gdext#540]
When GODOT4_BIN is set to a relative path, cargo build fails like this:

```
error: failed to run custom build command for `godot-codegen v0.1.0 (https://github.com/godot-rust/gdext?branch=master#ef5f388d)`

Caused by:
  process didn't exit successfully: `/home/punkt/p4/wasteoftimenumber6/rust_game/target/debug/build/godot-codegen-2d88935c4d152a29/build-script-build` (exit status: 101)
  --- stdout
  Found GODOT4_BIN with path to executable: '../godot/bin/godot.linuxbsd.editor.double.x86_64.llvm.mono'
  cargo:rerun-if-env-changed=GODOT4_BIN

  --- stderr
  thread 'main' panicked at /home/punkt/.cargo/git/checkouts/gdext-76630c89719e160c/ef5f388/godot-bindings/src/godot_exe.rs:278:56:
  failed to invoke command (read Godot version)
        "../godot/bin/godot.linuxbsd.editor.double.x86_64.llvm.mono" "--version"
```

The use case is that I have a variety of different workspaces on my machine that each have their own custom Godot editor built. If I could set GODOT4_BIN to a relative path, then I wouldn't need to set it differently for each project I'm working on.

And thanks for this project! Just getting my feet wet with it and I'm enjoying it.

**Comment by Bromeon** [comment]
Have you debugged and made sure that the path you specified is truly relative to the working directory in which that build.rs runs?

In general, I'm not sure if that is worth the trouble. Changing working directory would always break it. And I don't think relative paths are common in other toolchains, e.g. `JAVA_HOME`.

You could look into setting the env var depending on the project you're in, see for example https://stackoverflow.com/q/5848832.

**Comment by StagnationPoint** [comment]
It's correct relative to where cargo build is being invoked (aka in the same directory as the Cargo.toml file lives). New at Rust so not sure if that answers your question. Just used tab-completion to verify I'm setting the env var correctly:

`punkt@linus:~/p4/wasteoftimenumber6/rust_game$ GODOT4_BIN=../godot/bin/godot.linuxbsd.editor.double.x86_64.llvm.mono cargo build
<snip>
failed to invoke command (read Godot version)
        "../godot/bin/godot.linuxbsd.editor.double.x86_64.llvm.mono" "--version"
`

> You could look into setting the env var depending on the project you're in, see for example https://stackoverflow.com/q/5848832.

Thanks for the suggestion, that would solve it for command line usage, but means I still have to set it per project in my IDE, make sure Jenkins is doing the right thing, etc etc. All certainly straightforward enough, of course, just busy work in the absence of support for relative paths.

But if you don't think it's worthwhile, no worries, feel free to close the issue.

**Comment by Bromeon** [comment]
I think `build.rs` scripts do not run with the working directory of where `cargo` was invoked, but [their local source directory](https://doc.rust-lang.org/cargo/reference/build-scripts.html#inputs-to-the-build-script):
> In addition to environment variables, the build script’s current directory is the source directory of the build script’s package.

---

About the implementation, the path is read from the environment variable here, so directly put into a `PathBuf`:

https://github.com/godot-rust/gdext/blob/4ce4714b8871bf75e95d03401e44e3f1ccbdd7df/godot-bindings/src/godot_exe.rs#L261-L275

Later, it's used here in combination with `Command` to invoke Godot on the command line:

https://github.com/godot-rust/gdext/blob/4ce4714b8871bf75e95d03401e44e3f1ccbdd7df/godot-bindings/src/godot_exe.rs#L281-L297


Could you maybe add some `eprintln!` statements with your path and [the current working directory](https://doc.rust-lang.org/std/env/fn.current_dir.html#) and find out if the above hypothesis is correct? You can run `cargo build -vv` to print debug statements from `build.rs` scripts.

---

If that's the case, we need to see if it makes sense to change this, or if there are unintended downsides. Maybe we can call every external command with a different working directory, using [`Command::current_dir()`](https://doc.rust-lang.org/std/process/struct.Command.html#method.current_dir).

**Comment by Bromeon** [comment]
@StagnationPoint would you be interested in exploring the above hypothesis, and maybe coming up with a pull request to support relative paths?

**Comment by StagnationPoint** [comment]
@Bromeon Definitely. I'm new to Rust so I'm still trying to work out how to get cargo to pick up the changes I'm making in godot-bindings. :-)

**Comment by StagnationPoint** [comment]
I've investigated and the current working directory (std::env::current_dir()) is set to the gdext member project at this point in the build process, so in most (*nix) cases it will be something like:

```~/.cargo/git/checkouts/gdext-<hash>/<hash>/<member project>```

With this knowledge I was able to show that it actually *does* currently support a relative path for GODOT4_BIN, but there are two problems with this:

a) Since the current working dir is usually going to be starting out in the root of the user's home directory, any relative path would have to specify a specific workspace, which is what I was hoping to avoid in the first place.

b) Well, (a) makes this point moot, but: If the filesystem depth changes anywhere while running through the gdext build process -- e.g. if you've just figured out how to Cargo patch one member of the gdext project from your local filesystem so it's living in a different location than the other members :-) -- then the relative path will break. So in my case while it completed its version check successfully, it failed when outputting the manifest because that work originated from another part of my filesystem. A niche case but it could be a surprising break if a relative path is used in local gdext dev.

So I see a couple of options:

1) If it can't find the executable, and the GODOT4_BIN var is relative, have it combine the env var with the current working directory and see if it can find it that way. The drawback here is if the user is building from another working directory (say with "cargo build --manifest-path *path-to-user-project*/Cargo.toml"), I'd expect that to break. But there are lots of CLI tools that assume a certain working directory and we all deal with them, so I don't see this as a significant problem, and in any event it will only affect those using a relative path.

2) Look into whether it's possible to discover the location of the "owning" Cargo.toml file (i.e. the one in the user's game project) and look for the binary relative to that. I don't know enough about Cargo yet to say whether that would be difficult or easy, but I dumped all the CARGO_* env vars set by Cargo when godot-bindings was building and didn't see any promising candidates.

Thoughts?

**Comment by StagnationPoint** [comment]
Just found a better, pure-Cargo solution. In *path-to-user-project*/.cargo/config.toml [I can put](https://doc.rust-lang.org/cargo/reference/config.html):

```
[env]
GODOT4_BIN = { value = "../godot/bin/godot.linuxbsd.editor.double.x86_64.llvm.mono", relative = true }
```

And that does the business. I can modify my own build scripts to set this appropriately for the platform it's building on.

Thanks for your patience and guidance! Feel free to close the issue. If you'd be interested in a docs PR I could put that together.

**Comment by Bromeon** [comment]
Thanks a lot for these great findings! I would definitely appreciate if you could document the solution 🙂 

I think https://godot-rust.github.io/book/toolchain/godot-version.html might be the best candidate (the source code is [here](https://github.com/godot-rust/book/blob/master/src/toolchain/godot-version.md)). 
You could add a h3 section _Relative paths_ under _Custom Godot versions_.
