### ISSUE TITLE
`Engine::register_singleton` corrupts object ref count

### ISSUE THREAD

**Issue by TitanNano** [godot-rust/gdext#549]
# Steps to reproduce
1. download example project
2. compile rust lib
3. start project in editor
4. close editor

# Expected Outcome 
Engine closes normally

# Actual Outcome
Engine crashes during shutdown with `EXC_BAD_ACCESS`

# Details
When registering a recounted object as a singleton, the ref-count of the object is decremented after the registration while the engine keeps holding on to a pointer to the object.

This is demonstrated by the log output of the example project:

```bash
refcount (initial): 1 # the object has been created and we hold the only reference to it.
refcount (post-clone): 2 # smart pointer was cloned. There are now two references.
# second smart pointer is moved into Engine::register_singleton.
ref-count (post-register): 1 # Second smart pointer was dropped once the function returned. The engine did not increment the ref-count.
# original ref will be droped at the end of the scope.
```

Once the library tries to access the singleton again during shutdown, the engine crashes because the object has already been freed.

[ref-count-bug.zip](https://github.com/godot-rust/gdext/files/13796476/ref-count-bug.zip)

**Comment by TitanNano** [comment]
My current workaround for this is a manually managed wrapper for ref-counted singletons.

```rust
#[derive(GodotClass)]
#[class(base = Object, init)]
struct RefCountedSingleton {
    inner: Gd<RefCounted>,
}

impl RefCountedSingleton {
    fn new(object: Gd<RefCounted>) -> Gd<Self> {
        Gd::from_object(Self { inner: object })
    }

    fn get(&self) -> Gd<RefCounted> {
        self.inner.clone()
    }
}
```

**Comment by Bromeon** [comment]
Thanks! Duplicate of https://github.com/godot-rust/gdext/issues/522 I think?

**Comment by TitanNano** [comment]
Yes looks like a duplicate.
