### ISSUE TITLE
ScriptLanguageExtension methods can be called from multiple threads

### ISSUE THREAD

**Issue by TitanNano** [godot-rust/gdext#556]
I have encountered this while doing reimports of some assets. 

The method `ScriptLanguageExtension::frame` will be called for every frame in the main loop. In parallel, the engine might call `ScriptLanguageExtension::handles_global_class_type` from the import thread, which will cause a panic as `frame` is `&mut self`.

----
The quickest workaround is to not implement `ScriptLanguageExtension::frame`.

**Comment by Bromeon** [comment]
> The method `ScriptLanguageExtension::frame` will be called for every frame in the main loop. In parallel, the engine might call `ScriptLanguageExtension::handles_global_class_type` from the import thread, which will cause a panic as `frame` is `&mut self`.

Or maybe expose it without binding `&mut self`, similar to `#[func(gd_self)]` in other places?

**Comment by TitanNano** [comment]
@Bromeon this is certainly an option but if someone wants to perform mutable operations in `fn frame()` it would still panic in certain situations due to another thread holding an immutable reference.

I think (at least with `experimental-threads`) access to the class instance storage should block instead of panic.

**Comment by Bromeon** [comment]
@TitanNano What's the situation around this after recent `SiMut` changes?

**Comment by TitanNano** [comment]
@Bromeon unfortunately the changes to `ScriptInstance` are completely unrelated to this. 

Godot (particularly the editor) accesses `ScriptLanguage` singletons across multiple threads. Since `GdCell` panics on the second mutable borrow, this is an issue. It would be more ergonomic if `GdCell` would block the other thread until it becomes available instead of panicking.
