### ISSUE TITLE
Impl `Iterator::size_hint()` for `Dictionary` iterator types

### ISSUE THREAD

**Issue by ttencate** [godot-rust/gdext#560]
Follow-up to #559, logging it here so we won't forget.

**Comment by lilizoey** [comment]
We should also likely implement `ExactSizeIterator` where relevant

**Comment by tuto193** [comment]
Since https://github.com/godot-rust/gdext/pull/583 was already merged, this could be closed, right?

**Comment by Bromeon** [comment]
You're right, thanks.
In the future, you can write 

> Closes #560

directly in the initial PR message (not in the title, and no colon). That automates it.
