### ISSUE TITLE
Module `convert_error` is private

### ISSUE THREAD

**Issue by rymkapro** [godot-rust/gdext#568]
Hi everyone!

I'm trying to implement `FromGodot` trait, it wants 
`fn try_from_godot(via: Self::Via) -> Result<Self, godot::builtin::meta::convert_error::ConvertError> {}`, 
but `convert_error` module is private

What i'm doing wrong?

Thanks for your help!

**Comment by Bromeon** [comment]
You have the wrong module name:
https://godot-rust.github.io/docs/gdext/master/godot/builtin/meta/struct.ConvertError.html

**Comment by rymkapro** [comment]
Oh, thanks a lot!
It was my IDE, it suggested me wrong module it didn't see correct path
