### ISSUE TITLE
GDExt panics when two structs from different modules are named the same

### ISSUE THREAD

**Issue by AlexOkafor** [godot-rust/gdext#569]
Hello!
I recently got bitten by this and figured I'd pass it along for consideration for a bug fix or documentation clarification (I wasn't sure which was appropriate):
Essentially this snippet suggest this won't panic because rustc will complain:
```rust
 // The following unwraps of fill_into() shouldn't panic, since rustc will error if there are
 // multiple `impl I{Class} for Thing` definitions.

fill_into(&mut c.godot_params.create_instance_func, user_create_fn).unwrap();
```
https://github.com/godot-rust/gdext/blob/52628a0a8cb7d4c2d784a930261220ce3c0cb31d/godot-core/src/registry.rs#L380

### Problem
If you have a struct named `module_a::Foo` and `module_b::Foo` and they both implement the GodotClass derive macro, rust will compile, but upon launching the editor, the extension will panic:
```bash
ERROR: Rust function panicked in file C:\Users\Alex\.cargo\git\checkouts\gdext-76630c89719e160c\52628a0\godot-core\src\registry.rs at line 383. Context: failed to initialize GDExtension level `Scene`
   at: <function unset> (C:\Users\Alex\.cargo\git\checkouts\gdext-76630c89719e160c\52628a0\godot-core\src\lib.rs:161)
ERROR: Panic msg:  called `Result::unwrap()` on an `Err` value: ()
   at: <function unset> (C:\Users\Alex\.cargo\git\checkouts\gdext-76630c89719e160c\52628a0\godot-core\src\lib.rs:109)
ERROR: Rust function panicked in file C:\Users\Alex\.cargo\git\checkouts\gdext-76630c89719e160c\52628a0\godot-core\src\lib.rs at line 65. Context: failed to initialize GDExtension level `Editor`
   at: <function unset> (C:\Users\Alex\.cargo\git\checkouts\gdext-76630c89719e160c\52628a0\godot-core\src\lib.rs:161)
ERROR: Panic msg:  called `Result::unwrap()` on an `Err` value: PoisonError { .. }
   at: <function unset> (C:\Users\Alex\.cargo\git\checkouts\gdext-76630c89719e160c\52628a0\godot-core\src\lib.rs:109)
```

[Repo with minimal expample](https://github.com/AlexOkafor/gdext-repro-example) in case that's helpful.

I'm not sure if it's possible from the context of where this is being called, but it would be nice to have a clearer error message indicating that may be a possibility of what's happening as it was a bit of a headscratcher for me until I realized I had a naming collision via process of elimination of several structs.

**Comment by Bromeon** [comment]
Yep, a better error message should be possible.
