### ISSUE TITLE
`Gd<Self>` return type causes type error when fn annotated with `#[func]`

### ISSUE THREAD

**Issue by Lamby777** [godot-rust/gdext#578]
Sorry if dupe, mentioned this on the discord and @PgBiel said it was discussed before but might not have an issue open. From a quick search, I couldn't seem to find a thread for it.

The specific error:
```
can't use generic parameters from outer item
    use of generic parameter from outer item
```

Reproduce:

```rs
#[godot_api]
impl SomeCustomClass {
    // Uncomment the line below for a sussy wussy type error :D
    // #[func]
    pub fn do_some_stuff() -> Gd<Self> {
        todo!()
    }
}
```

**Comment by vortexofdoom** [comment]
Looked at this, it comes from the expansion here: https://github.com/godot-rust/gdext/blob/186ffcf482a5e475010af8c3bd61d0db52c8b5c2/godot-macros/src/class/data_models/func.rs#L58

When it generates the FFI, it uses the generic `Self` parameter, which Rust doesn't allow in nested functions.

The solution would probably be to parse the signature and manually turn `Self` into `SomeCustomClass` before passing it back. That *might* mess with syntax highlighting but I can fool around and see.

**Comment by vortexofdoom** [comment]
The `Monster` examples from [the book](https://godot-rust.github.io/book/register/functions.html) actually have this same problem. And if any arguments take a `Self` (specifically some other `Self`) they error as well.

So we'd probably have to parse the whole function and check everything for `Self`, not just the return type. It's probably something that's *technically* possible to support, but would require moderate instrumentation to be threaded into a fair amount of the parsing. As far as I've experimented, it only affects functions, so it's probably doable, but currently the function body isn't parsed in any way, it's just passed as tokens.

That being said, the given style for constructing a Gd from a closure has no problems, so we'd probably cover the majority of "correct" usage by just going through the signature.

The alternative of just trying to find a way to better document this is unsatisfying, as to get good errors we'd have to parse the tokens to report it in a useful way. It could just be added to the documentation of `Gd` but nothing would indicate to users that `Gd` is the problem, even though that should be the only place `Self` is used in a function signature.
