### ISSUE TITLE
Trying hot reload: Godot saying "initialize must only be called once" whenever I rebuild my Rust library

### ISSUE THREAD

**Issue by luciusmagn** [godot-rust/gdext#648]
I am pretty new to Godot, but I get this in the console. Is there any way I can prevent this error?

Hot reloading would be pretty nice, as I want to work with friends who will use the editor extensively for scenes

**Comment by Gurkinator1** [comment]
try adding the `experimental-threads` feature to your gdext dependency inside Cargo.toml

**Comment by luciusmagn** [comment]
Thanks a lot for the tip!

**Comment by Bromeon** [comment]
See also [this Discord](https://discord.com/channels/723850269347283004/1216844887409033268) thread.
