### ISSUE TITLE
Segfault when calling instance_from_id

### ISSUE THREAD

**Issue by alec-deason** [godot-rust/gdext#659]
Calling instance_from_id causes godot to segfault. I see the same behavior whether the instance id is valid or invalid. I would expect it to return a None in the case of an invalid id.

I'm seeing this on linux with godot 4.2.1. I have not tested it on other platforms.

This problem was introduced in commit bd76361a29a895ec522b78b052ae4b206fb45c8d

Attached is a minimal example demonstrating the crash. Compiling the rust part in crash_example/ and then running the godot part in godot/ should immediately segfault. Commenting out the gdext dependency in the Cargo.toml and uncommenting the alternate version, which points to the previous commit, should resolve the segfault.

[crash_example.tgz](https://github.com/godot-rust/gdext/files/14923285/crash_example.tgz)

**Comment by lilizoey** [comment]
found the issue, gonna try to write a test for it and then i'll make a PR

**Comment by Bromeon** [comment]
@alec-deason Is there a reason you use `instance_from_id()` instead of `Gd::try_from_instance_id()`/`Gd::from_instance_id()`?

**Comment by alec-deason** [comment]
@Bromeon Nope, `instance_from_id()` is just what I found when I went looking for the functionality. Is `Gd::try_from_instance_id()` preferred?

**Comment by Bromeon** [comment]
@alec-deason I would say yes, since it takes a typed `InstanceId`, which other APIs may also return.
