### ISSUE TITLE
Current master does not pass CI with current nightly

### ISSUE THREAD

**Issue by lilizoey** [godot-rust/gdext#661]
Not entirely sure what the issue is, but here's a full CI run i did:
https://github.com/lilizoey/gdextension/actions/runs/8669726868

Seems like the issue occurs somewhere in the [`instantiate_signals`](https://github.com/godot-rust/gdext/blob/18147d1439d64ecd64ef648eb9854379d8ca7795/itest/rust/src/builtin_tests/containers/signal_test.rs#L97) test or possibly the `signals` test before.

**Comment by Bromeon** [comment]
Hm, do you have any idea which Godot version might have introduced it (or at least when you saw it the first time)?
Otherwise I'll run a bisect later this weekend...

**Comment by lilizoey** [comment]
3 days ago #660 passed ci, at least

**Comment by lilizoey** [comment]
https://github.com/Bromeon/godot4-nightly/actions/runs/8640801516 this is the first nightly that fails

**Comment by Bromeon** [comment]
Looks like it's fixed in the meantime, current CI on master [passes](https://github.com/godot-rust/gdext/actions/runs/8681179849).
Not sure which PR fixed it, but it's not really important.
