### ISSUE TITLE
printerr before panic

### ISSUE THREAD

**Issue by rymkapro** [godot-rust/gdext#667]
Hi everyone!
Sorry if my question has already been answered..

I have a helper function for panic
```
pub fn godot_panic<T>(message: &str) -> T {
    printerr(message.to_variant(), &[]);
    godot_error!("{}", message);
    panic!();
}
```

i'm using it for unwapping, e.g. `.unwrap_or_else(|| godot_panic("message"))`
but nothing printed into the output

Is it possible to fix it, or i'm doing it in a wrong way?
Also i want to close the game on panic, but i didn't found how to quit() without node.base().get_tree().quit()

Thanks for your help!

**Comment by lilizoey** [comment]
panicking here may cause the prints to not get flushed to the console?

you should be able to use `Engine::singleton().get_main_loop().unwrap().to::<SceneTree>()` to access the scene tree. from there you can call `quit()`.

**Comment by rymkapro** [comment]
Oh, sorry for being late.
I've found a solution for me, may be it will be helpful for someone else
```
pub fn godot_panic<T>(message: &str) -> T {
    godot_error!("{}", message);
    godot::engine::Os::singleton()
        .alert_ex(message.into())
        .title("Critical error".into())
        .done();
    godot::engine::Engine::singleton()
        .get_main_loop()
        .unwrap()
        .free();
    panic!();
}
```

`panic!()` here needed only for <T>, because i use this function in `unwrap_or_else` and this panic is never called.
