### ISSUE TITLE
Dead link to safety chapter in book (docs)

### ISSUE THREAD

**Issue by jamesmcm** [godot-rust/gdext#675]
The link to https://godot-rust.github.io/book/gdext/advanced/safety.html is a dead link:

https://github.com/godot-rust/gdext/blob/master/godot-core/src/init/mod.rs#L183-L192

I'm not sure which page it should link to though.

**Comment by Bromeon** [comment]
This is something I still plan to add -- the page has been at 80% for a long time, will need to find some time for finishing touches...
