### ISSUE TITLE
Missing methods from built-in types

### ISSUE THREAD

**Issue by Ventilador** [godot-rust/gdext#681]
Several Godot built-in types have methods in the Godot Documentation, but they are not exposed in the rust API.
This is mostly for keeping track of them and people finding this and not creating new tickets.

Known types with missing methods:

> StringName: [godot](https://docs.godotengine.org/en/stable/classes/class_stringname.html#methods) vs [gdext](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.StringName.html#implementations).
> String : [godot](https://docs.godotengine.org/en/stable/classes/class_string.html#methods) vs [gdext](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.GString.html#implementations).
> NodePath: [godot](https://docs.godotengine.org/en/stable/classes/class_nodepath.html#methods) vs [gdext](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.NodePath.html#implementations)
> Callable (call_defered at least): [godot](https://docs.godotengine.org/en/stable/classes/class_callable.html#class-callable-method-call-deferred) vs [gdext](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.Callable.html#implementations) -- this one is nice because now the only way to defer is via `gd.call_defer(StringName, &[Variant])` which doesnt allow to store callbacks

**Comment by lilizoey** [comment]
i think this is a duplicate of https://github.com/godot-rust/gdext/issues/310 ?

**Comment by Ventilador** [comment]
seems like it my bad

**Comment by Ventilador** [comment]
seems like it my bad
