### ISSUE TITLE
GString (and possibly other variant types) are missing methods

### ISSUE THREAD

**Issue by RedMser** [godot-rust/gdext#684]
I am unsure if this is a documentation issue or a code generation issue, but here goes:

GString is missing helpful methods found in Godot such as `String.get_extension()` or `String.path_join()`. Searching the gdext API docs also reveals that this method does not exist.

This is contrary to the [GString documentation](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.GString.html) which reads as follows (my highlight):

> As a general guideline, use GString if:

> * your strings are very large, so you can avoid copying them
> * **you need specific operations only available in Godot (e.g. sha256_text(), c_escape(), …)**
> * you primarily pass them between different Godot APIs, without string processing in user code

Indeed, the listed methods here are also nowhere to be found. This might also be the case for other Variants, as StringName is also lacking a bunch of methods.

**Comment by RedMser** [comment]
Ah seems like the project status tracker issue includes variant type shortcomings as well.

So it's likely just documentation that was written with the assumption that these methods would be implemented soon.

Closing as a duplicate.

**Comment by Bromeon** [comment]
Please search before opening issues, this was just opened 2 days ago in https://github.com/godot-rust/gdext/issues/681 (and closed as duplicate as well). Thanks 😉
