### ISSUE TITLE
Trait bound 'Player: GodotDefault' is not satisfied error during Hello World example

### ISSUE THREAD

**Issue by PenguinOxide** [godot-rust/gdext#690]
Going step by step through the book, I copy/pasted everything in the Hello World section, including lib.rs as follows:
```
use godot::engine::Sprite2D;
use godot::prelude::*;

struct MyExtension;

#[gdextension]
unsafe impl ExtensionLibrary for MyExtension {}

#[derive(GodotClass)]
#[class(base=Sprite2D)]
struct Player {
    speed: f64,
    angular_speed: f64,
    base: Base<Sprite2D>,
}
```

I always get the following error on the Player struct:

```
rustc: the trait bound `Player: GodotDefault` is not satisfied
the following other types implement trait `GodotDefault`:
  AesContext
  AStar2D
  AStar3D
  AStarGrid2D
  AcceptDialog
  AnimatableBody2D
  AnimatableBody3D
  AnimatedSprite2D
and 707 others [E0277]
```
Cargo.toml for reference:
```
[package]
name = "further"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]  # Compile this crate to a dynamic C library.

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
```
Any ideas as to what may be causing this issue?

**Comment by GsLogiMaker** [comment]
Is it because no_init is not passed to the class macro and it has no init implementation?

**Comment by PenguinOxide** [comment]
Thank you for your response! Added the `impl ISprite2d for Player` block with the init() function and that did the trick. I guess I assumed that the existence of Godot's default init() function would make overriding it locally not strictly required. That's my bad. 

Thanks again for responding.

**Comment by Bromeon** [comment]
With a new Rust feature released yesterday, we can also improve this error message 🙂 I already planned to work on it this weekend.
