### ISSUE TITLE
Virtual function dispatch for Resources not working

### ISSUE THREAD

**Issue by mio991** [godot-rust/gdext#698]
If I have a CustomResource like this:
```rust
#[derive(GodotClass)]
#[class(init, base=Resource)]
pub struct BaseResource {
    _base: Base<Resource>,
}

#[godot_api]
impl BaseResource {
    #[func(virtual, rename = _get_value)]
    pub fn get_value(&self) -> GString {
        unimplemented!("get_value should be overridden");
    }
}
```

and extend it into an actual implementation like this:
```gdscript
extends BaseResource
class_name TestResource

func _get_value() -> String:
	return "Lila"
```

I get an Unimplemented Error, if I try to call `get_value()` from rust like so:

```rust
impl BaseResource {
    pub fn test_virtual(&self) {
        godot_print!("Value: {}", self.get_value());
    }
}
```

### Reproduction Steps

1. decrompress [demo.zip](https://github.com/godot-rust/gdext/files/15210383/virtual-resource-functions.zip)
2. add [Godot 4.3-dev6](https://godotengine.org/download/archive/4.3-dev6/) in the `./bin` folder
3. build the rust library
4. start Godot 4.3-dev6
5. open the Project under `./godot`
6. execute `main.tscn`
7. click the Test-Button

There are Exceptions in the Output.

### Expected Behaviour

I expect a console output of `Value: Lila`.

**Comment by Bromeon** [comment]
Can you please describe the problem in a minimal complete example here, so users don't need to download a ZIP package? Thanks!

**Comment by mio991** [comment]
I edited my initial Comment, I hope that helps. I can also push the demo Project from the zip file t github if you want.

**Comment by Bromeon** [comment]
I meant http://www.sscce.org, i.e. a small code example that is enough to demonstrate the problem, focuses _only_ on the problem and removes anything that's not absolutely necessary. But it's still self-contained, so others can quickly test it, without the need to download + compile + load the whole project.

Don't get me wrong, the .zip can still be useful, but it should be an _addition_ to the actual problem description. It must be possible to understand and discuss the issue without download.

Thanks for your understanding! :slightly_smiling_face:

**Comment by lilizoey** [comment]
I think if you want virtual methods like this to work you'll have to call them like
```rs
self.base().call("test_virtual".into(), &[]);
```
because otherwise you'll just end up calling the rust function.

maybe we should change this so that the `godot_api` macro automatically overwrites the original rust function to do something like the call above?

**Comment by Bromeon** [comment]
One issue with GDScript inheriting Rust `Resource` has been fixed along with https://github.com/godotengine/godot/issues/93676. I'll close this, if the issue persists, please come up with a SSCCE as requested two months ago 🙂
