### ISSUE TITLE
Simple VideoStreamPlayback causes thread panic

### ISSUE THREAD

**Issue by funatsufumiya** [godot-rust/gdext#709]
I just created `VideoStreamPlayback` as just simple as possible (with dummy data), causes thread error.
https://github.com/funatsufumiya/godot_test_video_stream

- code: [src/lib.rs](https://github.com/funatsufumiya/godot_test_video_stream/blob/main/rust/src/lib.rs)

First error shows `use the "experimental-threads" feature`, but when enabled it, still panic occurs when some audio IOThread interrupted.

```text
thread '<unnamed>' panicked at /xxx/.cargo/git/checkouts/gdext-76630c89719e160c/8163134/godot-ffi/src/binding/single_threaded.rs:100:13:
assertion `left == right` failed: attempted to access binding from different thread than main thread; this is UB - use the "experimental-threads" feature.
  left: ThreadId(1)
 right: ThreadId(2)
```

```text
thread '<unnamed>' panicked at /xxx/.cargo/git/checkouts/gdext-76630c89719e160c/8163134/godot-core/src/storage/multi_threaded.rs:59:13:
Gd<T>::bind() failed, already bound; T = godot_test_video_stream::TestVideoStreamPlayback.
  Make sure to use `self.base_mut()` or `self.base()` instead of `self.to_gd()` when possible.
  Details: cannot borrow while accessible mutable borrow exists.
```

- Full error log (backtrace) without `experimental-threads`:
[error_without_experimental_threads.txt](https://github.com/funatsufumiya/godot_test_video_stream/blob/main/error_logs/error_without_experimental_threads.txt)

- Full error log (backtrace) with `experimental-threads`:
[error_with_experimental_threads.txt](https://github.com/funatsufumiya/godot_test_video_stream/blob/main/error_logs/error_with_experimental_threads.txt)

- Error report from macOS (also same error occurs on Windows):
[error_report_mac.txt](https://github.com/funatsufumiya/godot_test_video_stream/blob/main/error_logs/error_report_mac.txt)

**Comment by Bromeon** [comment]
> First error shows `use the "experimental-threads" feature`, but when enabled it, still panic occurs when some audio IOThread interrupted.

Can you elaborate on this error? I assume the panic is different?

**Comment by funatsufumiya** [comment]
@Bromeon 
Probably the reason of the panic is the same. But I don't know what is happening behind, maybe some audio event about video processing, but this example doesn't treat any audios.

**Comment by funatsufumiya** [comment]
Thank you very much for fixing this bug. I confirmed it and updated my example's `Cargo.lock`: https://github.com/funatsufumiya/godot_test_video_stream

**Comment by Bromeon** [comment]
Thanks for testing, glad to hear it works! 
The credits really go to @TitanNano who has done an amazing job with the script instance APIs! :muscle:
