### ISSUE TITLE
commit() failing for SurfaceTool in simple case

### ISSUE THREAD

**Issue by ColmMathews** [godot-rust/gdext#718]
Builds without error. Crashes at commit() in godot on run

Minimum reproducible example
```rs
use godot::engine::mesh::PrimitiveType;
use godot::engine::Mesh;
use godot::prelude::*;

use godot::engine::MeshInstance3D;
use godot::engine::SurfaceTool;

use godot::engine::IMeshInstance3D;

#[derive(GodotClass)]
#[class(base=MeshInstance3D)]
struct Map {
    base: Base<MeshInstance3D>,
}

#[godot_api]
impl IMeshInstance3D for Map {
    fn init(base: Base<MeshInstance3D>) -> Self {
        godot_print!("Hello, surface tool!1");
        Self {
            base,
        }
    }

    fn ready(&mut self) {
        
        godot_print!("here");
        godot_print!("surface tool ready");
        let mut st = SurfaceTool::new_gd();
        st.begin(PrimitiveType::TRIANGLES);

        //# Prepare attributes for add_vertex.
        st.set_normal(Vector3::new(0.0, 0.0, 1.0));
        st.set_uv(Vector2::new(0.0, 0.0));

        //# Call last for each vertex, adds the above attributes.
        st.add_vertex(Vector3::new(-1.0, -1.0, 0.0));
        
        st.set_normal(Vector3::new(0.0, 0.0, 1.0));
        st.set_uv(Vector2::new(0.0, 1.0));
        st.add_vertex(Vector3::new(-1.0, 1.0, 0.0));
        
        st.set_normal(Vector3::new(0.0, 0.0, 1.0));
        st.set_uv(Vector2::new(1.0, 1.0));
        st.add_vertex(Vector3::new(1.0, 1.0, 0.0));

        let a_mesh = st.commit();
        match a_mesh {
            Some(m) => {
                godot_print!("mesh exists");
                let mm: Gd<Mesh> = m.upcast::<Mesh>();
                self.base_mut().set_mesh(mm);
            },
            None => godot_print!("no mesh"),
        }
    }
}
```

**Comment by Bromeon** [comment]
Does the equivalent code in GDScript work?
What does "crash" mean, can you show the standard error output on the terminal?

Please also use Rust code tags for _all_ your code, it helps readability. Start blocks with ` ```rs `. Thanks! 🙂

**Comment by lilizoey** [comment]
`commit` takes an optional param that is a null-object, so i think this is a duplicate of #156. you should have gotten an error message from the crash pointing to that issue? maybe try running with the console if you didnt.

**Comment by ColmMathews** [comment]
Thank you kindly, really appreciate the help.

**Comment by clsulli95** [comment]
can we update the example with the fix?  Following other language tutorials for Godot and implementing with godot-rust and running into this same issue.  Other language bindings are just calling `.commit()`.

**Comment by clsulli95** [comment]
Sorry, found answer in the linked issue.  Is suggested workaround still the solution in this case?  For anyone that comes across, suggested workaround is linked [here](https://github.com/godot-rust/gdext/issues/156#issuecomment-1823717967)

**Comment by Bromeon** [comment]
Yes, that's still the case. The workaround is also mentioned in the initial message of that issue.
