### ISSUE TITLE
godot endlessly prompting to restart

### ISSUE THREAD

**Issue by backwardspy** [godot-rust/gdext#722]
i followed the [hello world](https://godot-rust.github.io/book/intro/hello-world.html) section of the godot rust book and it's all working as expected. there is just one issue i'm running into.

when i open my project in godot, i get this popup:
![image](https://github.com/godot-rust/gdext/assets/289746/b951102b-ed61-4a91-8836-df42394456ae)

i can click `continue` and run my game, and everything works properly. however every time i re-focus the godot window, the message comes back. if i instead click `save & restart`, godot restarts and immediately prompts me to restart it again. this goes on endlessly.

info from the "output" tab:

```
Godot Engine v4.2.2.stable.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started ---
--- GDScript language server started on port 6005 ---
hello from rust
  core/extension/gdextension.cpp:778 - Parameter "library" is null.
hello from rust
  core/extension/gdextension.cpp:778 - Parameter "library" is null.
  core/extension/gdextension.cpp:778 - Parameter "library" is null.
  core/extension/gdextension.cpp:778 - Parameter "library" is null.
  core/extension/gdextension.cpp:778 - Parameter "library" is null.
```
"hello from rust" is from my code. the other message repeats every time i choose `continue`.

i've searched through other issues and i haven't been able to find anything that solves this. i've tried changing the `reloadable` property in my gdextension file but that made no difference.

**additional info:**
platform: windows 11
godot version: v4.2.2.stable.official [15073afe3]
rust version: rustc 1.78.0 (9b00956e5 2024-04-29)

please let me know if there's anything else i can provide. thanks for the awesome project!

**Comment by Bromeon** [comment]
Very strange, I haven't seen this yet.

If you clone this repo, build the `dodge-the-creeps` example (`cargo build -p dodge-the-creeps`) and open the editor from that folder (`godot4 --path examples/dodge-the-creeps/godot`)... does the issue also appear?

**Comment by Bromeon** [comment]
Make sure to use version control (git) and check in the project files, also for Godot -- that way, it's easier to detect accidental changes and revert to known good states.

Glad to hear a fresh project solved it!

**Comment by backwardspy** [comment]
yeah i definitely should have done :) thanks!
