### ISSUE TITLE
Can't export variable with suffix

### ISSUE THREAD

**Issue by TheTrueWhiteOwl** [godot-rust/gdext#731]
I cannot recreate the following gdscript code in rust:
`@export_range(0, 10000, 1, "or_greater", "suffix:ms") var delay: int = 1000`
Specifically this part __________________________^^^^^^^

I have tried to find how to do this in the documentation, but it is very empty, devoid of examples and still very unhelpful right now.

Is there a way to support this? Maybe something like this?
`#[export(range=(0,1000,1,or_greater), suffix="ms")]`
But I hope you understand I have no clue exactly how attributes work or how this feature could be implemented.

**Comment by lilizoey** [comment]
i was not aware this is something you could do in gdscript? do you know where this is documented?

**Comment by lilizoey** [comment]
as a workaround, it should be possible to do 
```rs
#[export]
#[var(
    hint = RANGE,
    hint_string = "write your custom hint string here",   
)]
```
if you know what the hint string should look like

**Comment by StatisMike** [comment]
@lilizoey Seems to be available only for export_range:

https://docs.godotengine.org/en/stable/classes/class_%40gdscript.html#class-gdscript-annotation-export-range
