### ISSUE TITLE
Can't set Input default cursor shape

### ISSUE THREAD

**Issue by arslan2012** [godot-rust/gdext#763]
The input singleton has the set_default_cursor_shape method but does not have any input parameters, rendering the method useless
https://godot-rust.github.io/docs/gdext/master/godot/engine/struct.Input.html#method.set_default_cursor_shape

### Expected behavior
it should accept a cursorShape parameter, just like the one in Control::set_default_cursor_shape does
https://godot-rust.github.io/docs/gdext/master/godot/engine/struct.Control.html#method.set_default_cursor_shape

**Comment by Bromeon** [comment]
> The input singleton has the set_default_cursor_shape method but does not have any input parameters, rendering the method useless https://godot-rust.github.io/docs/gdext/master/godot/engine/struct.Input.html#method.set_default_cursor_shape

Check one line below 😉 

Please also read the book, this is explained: https://godot-rust.github.io/book/godot-api/functions.html#default-parameters
