### ISSUE TITLE
Passing an inherited class to a base class required function

### ISSUE THREAD

**Issue by IsotoxalDev** [godot-rust/gdext#765]
A function requires Texture2D, but I only have an ImageTexture and there is no way to convert ImageTexture to Texture2D as Texture2D is a base class.
![image](https://github.com/godot-rust/gdext/assets/62714538/faa0e48a-cbd9-49a3-92c4-a7d4641382ce)

Passing ImageTexture to Texture2D works in gdscript, so hoping for a similar solution

**Comment by Pspritechologist** [comment]
This is where upcasting comes in since Rust doesn't have *actual* inheritance, it's how you get a base class from one that inherits it. 
You can find it in the book.

**Comment by IsotoxalDev** [comment]
oh thanks didn't knew about it.....
