### ISSUE TITLE
No duration argument for add_frame function of SpriteFrames

### ISSUE THREAD

**Issue by IsotoxalDev** [godot-rust/gdext#766]
This is in the gd rust docs
![image](https://github.com/godot-rust/gdext/assets/62714538/c91a9fed-bd4d-4f7e-b137-f121e5587009)

the function's doc in godot documentation
![image](https://github.com/godot-rust/gdext/assets/62714538/d13ac6ea-8ae5-4272-96bc-0207027ecafd)

**Comment by Bromeon** [comment]
Please check book and docs before opening issues. Default parameters are supported differently.

See also  #763 🙂

**Comment by IsotoxalDev** [comment]
Sorry Thanks for the help!!
