### ISSUE TITLE
`impl Export for PackedScene`?

### ISSUE THREAD

**Issue by maltalef101** [godot-rust/gdext#786]
can and should this be done? it's possible to do so from gdscript files. i am not aware of limitations to the gdextension api.
i have a use case where this would be useful, but i'll be looking into alternative implementations if this feature is too much of a hassle.

**Comment by Bromeon** [comment]
The Godot types are never used by-value, so you won't be able to declare a field of type `PackedScene`.

Can you use `Gd<PackedScene>` instead?
