### ISSUE TITLE
[Performance Issue] Extra calls to std::write

### ISSUE THREAD

**Issue by Ughuuu** [godot-rust/gdext#791]
On my [performance investigation](https://github.com/appsinacup/godot-rapier-physics/issues/139) I saw a spike in the usage of the function `std::write` in release mode. This comes from `godot-ffi/src/toolbox.rs`:

```rust
/// Trace output.
#[cfg(not(feature = "debug-log"))]
// TODO find a better way than sink-writing to avoid warnings, #[allow(unused_variables)] doesn't work
#[macro_export]
 macro_rules! out {
     ()                          => ({});
     ($fmt:literal)              => ({ use std::io::{sink, Write}; let _ = write!(sink(), $fmt); });
     ($fmt:literal, $($arg:tt)*) => ({ use std::io::{sink, Write}; let _ = write!(sink(), $fmt, $($arg)*); };)
 }
```

Here, even though it doesn't need to write, as it's not in release mode, it does call write.

For this, simply doing:

```rust
#[cfg(not(feature = "debug-log"))]
// TODO find a better way than sink-writing to avoid warnings, #[allow(unused_variables)] doesn't work
 #[macro_export]
 macro_rules! out {
     ()                          => ({});
     ($fmt:literal)              => ({});
     ($fmt:literal, $($arg:tt)*) => ({});
 }
```

Fixes the issue.

**Comment by Bromeon** [comment]
> ```rust
> // TODO find a better way than sink-writing to avoid warnings, #[allow(unused_variables)] doesn't work
> ```

That line explains why this isn't done -- we need to "use" the variables somehow, or check if there's another way to suppress the warning. Maybe it's also no longer the case.

**Comment by Ughuuu** [comment]
Sure, no worries, didn't mean to point fingers or anything, it's just a result of the performance investigation I found, listed in this repo as issues. Thanks for the insight into the code and as to why it might be like this.

**Comment by Dheatly23** [comment]
This seem to fix the issue:

```rust

/// Trace output.
#[macro_export]
macro_rules! out {
    ($($arg:tt)*) => (if $crate::__DEBUG_LOG {
        eprintln!($($arg)*);
    });
}

// Helper constant for out macro.
#[doc(hidden)]
pub const __DEBUG_LOG: bool = cfg!(feature = "debug-log");
```

Basically it mimics `debug_assert` macro. I assign `cfg` result in a constant because feature check only works in the original crate. Testing the assembly output shows no code is emitted when the flag is off.
