### ISSUE TITLE
How to use signals between GDScript and Rust?

### ISSUE THREAD

**Issue by CocytusDEDI** [godot-rust/gdext#803]
## Question
Examples show how to use signals between rust code, but not for between GDScript and Rust as far as I could see. I couldn't find much, but this was my best attempt:
Signal emit:
```
self.base_mut().emit_signal("component_cast".into(), &[Variant::from(*component_code)]);
```

Signal connection & definition:
```
#[godot_api]
impl Spell {
    #[func]
    fn connect_player(&mut self, &mut player: Gd<Node>) {
        let update_function = player.callable("update_component_call_count");
        player.connect("component_cast".into(), update_function);
    }

    #[signal]
    fn component_cast(component_code: u64);
}
```

GDScript function to call:
```
func update_component_call_count(component_code):
	print(component_code)
```

In the `_ready` GDScript function I call `var test_spell = Spell.new()` and `test_spell.connect_player(self)`. I am adding the test_spell to the scene, and I know the test_spell works from other tests. My code compiles but when run it never prints anything, my spell instance works fine other than the fact that the signal isn't doing anything, and I know the emit signal line is being called thanks to a godot_print statement next to it.

If you're looking for more context, the rest of the code is [here](https://github.com/CocytusDEDI/MMSpellbook), but anything to do with signals isn't committed yet and the GDScript code isn't included.

**Comment by Yarwin** [comment]
You are supposed to connect Spell's component_cast signal to Gd<Node>, not the other way around :).

Example:
```rust
use godot::prelude::*;
use godot::classes::{Timer};

struct MyExtension;


#[derive(GodotClass)]
#[class(init, base=Node2D)]
pub struct SomeCaller {
    #[export]
    timer: Option<Gd<Timer>>,
    #[export]
    listener: Option<Gd<Node>>,
    base: Base<Node2D>,
}

#[godot_api]
impl INode2D for SomeCaller {
    fn ready(&mut self) {
        let callable = self.base().callable("on_timer_timeout");
        self.timer.as_mut().unwrap().connect("timeout".into(), callable);
        if let Some(listener) = self.listener.as_mut() {
            let update_function = listener.callable("some_gdscript_method");
            self.base_mut().connect("my_cool_rust_signal".into(), update_function);
        }
    }
}

#[godot_api]
impl SomeCaller {
    #[func]
    fn on_timer_timeout(&mut self) {
        godot_print!("timer timeout!");
        self.base_mut().emit_signal("my_cool_rust_signal".into(), &[]);
    }

    #[signal]
    fn my_cool_rust_signal();
}

#[gdextension]
unsafe impl ExtensionLibrary for MyExtension {}
```

```
extends Node


func some_gdscript_method():
	print("I just recieved rust signal!")
```
![image](https://github.com/user-attachments/assets/5aa3f461-c506-45ae-aac4-c6bd9061fab0)

**Comment by Yarwin** [comment]
Side note – Godot exposes methods that allow one to check all the connections and whatnot: https://docs.godotengine.org/en/latest/classes/class_object.html#class-object-method-get-signal-connection-list, might come in handy while debugging (Especially when combined with godot's expression/dev console)

**Comment by CocytusDEDI** [comment]
Thanks for the help! I've got it to emit a signal now :)
