### ISSUE TITLE
Unable to get auto completion on node classes

### ISSUE THREAD

**Issue by amg98** [godot-rust/gdext#813]
I have tried using this crate and I'm unable to get intellisense working for node classes anymore (inside godot::classes module). It still works for derive macros though.

The project compiles and runs fine, it's just that Im not getting auto completions for those classes

I'm using rust analyzer with default options on vscode, are you using any specific options to fix this?

**Comment by Bromeon** [comment]
> anymore [...] still

That means it worked before? What changed?

I'm not on VSCode myself, but on Discord some people have discussed similar issues in the past 🤔

**Comment by amg98** [comment]
@Bromeon Several months ago I gave the crate a try and I was able to autocomplete back then, that's why I have mentioned "anymore". I just tried downgrading the crate version until 0.1.0 but still no luck. If I downgrade beyond 0.1.0 the crate is unable to be resolved when adding it using `cargo add`.

I'm using latest vscode version with rust analyzer extension. The LSP version is 2024-07-22 (the latest as well at the time of writing)

Looks that it must be something related to rust analyzer not being able to get the generated code under the `OUT_DIR` folder, but I couldn't find any configuration options in the LSP related to this. Probably it's just a bug in rust analyzer as the crate is compiling fine, I don't know.

I have prepared a repro here https://github.com/amg98/gdextrust-repro in case someone can try it out. I also tried using nvim with rust analyzer lsp but I have exactly the same issue (using the latest rust analyzer version with default config)

**Comment by lmsonic** [comment]
I think I had this issue in the newest version of rust analyser, and downgrading to last week made it work again, try that!

**Comment by kyle-watson** [comment]
I just cloned your repo and it seems to be working for me. Can you post an example function or usage that I would be able to test? Are you using `self.base` instead of `self.base()` or `self.base_mut()`? That could be one cause.

**Comment by amg98** [comment]
> I think I had this issue in the newest version of rust analyser, and downgrading to the previous made it work again, try that!

Yeah, it was a rust analyzer bug, I installed last week's version and the error is gone. Thank you so much! I'll report this issue in rust analyzer repo so it is fixed asap
