### ISSUE TITLE
`Key` type makes `KeyMask | Key` combinations impossible without `.call()` hacks

### ISSUE THREAD

**Issue by StatisMike** [godot-rust/gdext#818]
Maybe I am mistaken, but from what I've seen, the `Key` restriction (especially in regards to builtin methods) makes the key + mask combinations impossible with types.

Eg., given such code (in context of some Class method):

```rust
let menu = self.base().get_node_as::<MenuButton>("Toolbar/MenuButton");
let mut menu_popup = menu.get_popup().unwrap();

menu_popup
   .add_item_ex("Add scene".into())
   // Line below doesn't work, as `.accel` expects `Key`
   .accel(KeyModifierMask::CMD_OR_CTRL | Key::A)
   .done();
```

Whereas in GDScript-land:

```php
menu_popup.add_item("Add scene", KEY_MASK_CMD_OR_CTRL | KEY_A)
```

Can be worked out using `Object::call()` method, but losing on type safety.

Maybe it could be worked out by allowing internal modification of `Key`? 

```rust
let mut key_with_mask = Key::A;
key_with_mask.with_mask(KeyModifierMask::CMD_OR_CTRL);
```

Didn't test out if more complex operations than applying one KeyModifierMask on `KEY_*` consts are valid in Godot.

**Comment by Bromeon** [comment]
Good catch. It seems like we need to explicitly support this.

It also means `Key` could not be an `enum` in this case. Or it would need to be accompanied by a `MaskedKey` struct which also stores modifiers.

**Comment by StatisMike** [comment]
Maybe something like a `KeyInput` trait, which will be implemented for both `Key` enum const and new struct being combination key and mask.

**Comment by Bromeon** [comment]
I worry about trait overengineering for this specific case, which then requires knowledge of 4 different symbols for something as simple as keys:
- `Key` enum
- `KeyModifierMask` enum
- `KeyWithMask` struct
- `AsKey` trait

I'm not sure if people truly need to be able to differentiate between keys and (keys+modifiers). I mean, in GDScript, C++, C# (?) they cannot either, and it doesn't seem to be a problem. 

But yeah, we need to _somehow_ modify the generated types anyway... but maybe just adding a `|` operator that returns again `Key` is enough. It's a constant and not a key, after all.
