### ISSUE TITLE
Invalid syntax in docs xml

### ISSUE THREAD

**Issue by andreymal** [godot-rust/gdext#837]
I literally copied [godot/tests/docs.rs](https://github.com/godot-rust/gdext/blob/87fa9baec74b2ec142a57438033f71ada3b0e976/godot/tests/docs.rs) into a new project and got this:

<a href="https://github.com/user-attachments/assets/8cb77a07-7a00-44da-827e-572daf790cae"><img src="https://github.com/user-attachments/assets/8cb77a07-7a00-44da-827e-572daf790cae" height="256px"/></a>

Same happens with code blocks like these:

    /// some html snippets inside docstring:
    ///
    /// `foo <em>bar</em>`
    ///
    /// ```html
    /// foo <u>bar</u>
    /// ```

Replacing `<` with `&amp;lt;` (double escaping because markdown unescapes one) fixes everything.

So I suspect that doc strings must be escaped somewhere?

**Comment by Bromeon** [comment]
Thanks for pointing these out! Doc registration is a very recent feature (https://github.com/godot-rust/gdext/pull/748), so some parts are not yet ironed out.

Would you be interested in submitting a pull request to address some of the points you mentioned? Someone else recently made a similar PR https://github.com/godot-rust/gdext/pull/815, which could serve as inspiration. We can of course gladly assist and guide you in case of questions! :slightly_smiling_face:
