### ISSUE TITLE
Threaded resource loading is disabled

### ISSUE THREAD

**Issue by TitanNano** [godot-rust/gdext#854]
I would like to use threaded resource loading, but the API for it has been disabled here https://github.com/godot-rust/gdext/commit/90da5aed0f5804e990dab439a15eb5b009f5191d. 

Has this been disabled because custom resources (defined in rust) shouldn't be loaded outside the main thread? Are there other issues blocking this API? 

I wasn't able to find a motivation for the removal. Can we add these APIs to the `experimental-threads` feature?

**Comment by Bromeon** [comment]
They were disabled in November 2022, long before we even had experimental threading.
So yes, I think they can be re-added as long as they're feature-gated in `experimental-threads` 👍
