### ISSUE TITLE
GDScriptFunctionState, Async implementation.

### ISSUE THREAD

**Issue by darthLeviN** [godot-rust/gdext#868]
My suggestion  is to expose `GDSCriptFunctionState` and implement `Future` for it or it's wrappers.

I wanted to do this but i read that i should make an issue and discuss it first because it's big change.

Is this a useful thing to enable seamless await/async calls in the future?

**Comment by TitanNano** [comment]
`GDSCriptFunctionState` exposes a `connected` signal, so if #261 gets implemented, we can convert the function state into a signal future.

**Comment by Bromeon** [comment]
Please continue discussion under #261, there are ongoing ideas/efforts.
