### ISSUE TITLE
Build failed for x86_64-apply Darwin

### ISSUE THREAD

**Issue by cherish-ltt** [godot-rust/gdext#877]
run
`cargo build --target=x86_64-apple-darwin`
`cargo:warning=cc.exe: error: unrecognized debug output level 'full'
 cargo:warning=cc.exe: error: unrecognized command-line option '-mmacosx-version-min=10.7'
 cargo:warning=cc.exe: error: unrecognized command-line option '-arch'`

from Windows to Mac

**Comment by lilizoey** [comment]
can you build other unrelated rust projects for `x86_64-apple-darwin`?

**Comment by cherish-ltt** [comment]
> can you build other unrelated rust projects for `x86_64-apple-darwin`?

problem solved：[users.rust-lang.org](https://users.rust-lang.org/t/failed-to-run-custom-build-command-for-ring-v0-17-8/116812)
