### ISSUE TITLE
platform/windows/os_windows.cpp:383 - Condition "!FileAccess::exists(path)" is true. Returning: ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by hwyrq** [godot-rust/gdext#882]
platform/windows/os_windows.cpp:383 - Condition "!FileAccess::exists(path)" is true. Returning: ERR_FILE_NOT_FOUND
 platform/windows/os_windows.cpp:383 - Condition "!FileAccess::exists(path)" is true. Returning: ERR_FILE_NOT_FOUND
  GDExtension dynamic library not found: D:/RustroverProjects/godot/godot-3d/target/debug/godot-3d.dll

**Comment by Bromeon** [comment]
Ok, enough spam. https://github.com/godot-rust/gdext/issues/881
