### ISSUE TITLE
Quaternion - Vector3 Multiplication operator

### ISSUE THREAD

**Issue by theKidOfArcrania** [godot-rust/gdext#893]
the [* operator](https://docs.godotengine.org/en/stable/classes/class_quaternion.html#class-quaternion-operator-mul-vector3) for quaternion * vector3 is missing

**Comment by Bromeon** [comment]
Thanks for reporting! Would you have time to submit a pull request? 🙂

**Comment by theKidOfArcrania** [comment]
Yeah submitted. Would it be considered the best practice to just use glam's libraries when possible?

**Comment by Bromeon** [comment]
Thanks a lot! :+1: 

Yes I think that's fine, especially for more complex operations. We can always change it in the future :slightly_smiling_face:
