### ISSUE TITLE
Utilities to work with the node tree

### ISSUE THREAD

**Issue by Bromeon** [godot-rust/gdext#9]
Similar to the old `NodeResolveExt`, utility methods would allow more idiomatic access to the scene tree.
Those could be provided as an extension trait or in a dedicated module/struct.

Examples:

- [x] `get_node<T>`
- [x] `find_node<T>` (optional) -- implemented as `try_get_node`
- [x] `load<T>`
- [x] `PackedScene::instance<T>`

**Comment by HenryWConklin** [comment]
Seems like get_node and load are implemented. https://github.com/godot-rust/gdext/blob/08c65941ce544b2255d5b09168c7e9944a9dd454/godot-core/src/engine.rs#L25-L46

Is `PackedScene::instance<T>` the only item left on this?

**Comment by Bromeon** [comment]
There might be other similar methods 🙂

**Comment by Cankyre** [comment]
Hoi, is this up-to-date? I can work on some of the features.

**Comment by Bromeon** [comment]
#299 implemented `instantiate_as`, so it's complete. 

I'll close this, if you have other good examples, let me know. But don't find some just for the sake of it, it should be common operations 😉
