### ISSUE TITLE
Feasability for implementing Eq on Gd

### ISSUE THREAD

**Issue by Soremwar** [godot-rust/gdext#909]
Behind the scenes this would work by comparing the instance id of the nodes allowing us to do something like `my_node == &my_node`

This is a valid approach however not very common in the GDScript community, perhaps for a technical reason I'm overlooking, hence the need to open an issue

I'm open to implementing this feature if you think it would be a good addition for the project

**Comment by Bromeon** [comment]
Did you check the docs?
https://godot-rust.github.io/docs/gdext/master/godot/obj/struct.Gd.html#impl-Eq-for-Gd%3CT%3E

**Comment by Soremwar** [comment]
My bad :smile:
