### ISSUE TITLE
Adding representations for custom nodes

### ISSUE THREAD

**Issue by Soremwar** [godot-rust/gdext#921]
What would be the correct way to represent an object registered by say an addon inside gdext?

**Comment by Bromeon** [comment]
Could you elaborate?

If you mean generating Rust code for external classes, see here:
https://github.com/godot-rust/gdext/issues/615

**Comment by Soremwar** [comment]
Thanks, yes that's what I meant

Gonna close referencing other issues talking about this #724 #372
