### ISSUE TITLE
Implement `BitOr` for common enum types

### ISSUE THREAD

**Issue by QueenOfSquiggles** [godot-rust/gdext#954]
Hey hey. Enum flags could be more intuitive to use if implementing the `BitOr` trait, which enables support for cases such as:

```rust
.connect_ex( /* */ )
  .flags(ConnectFlags::DEFERRED | ConnectFlags::ONE_SHOT)
  .done();
```

further docs for this trait are available [here](https://doc.rust-lang.org/std/ops/trait.BitOr.html)

A potential implementation could look like:

```rust

impl BitOr for ENUM_STRUCT {
  type Output = i32; // or other via type

  fn bitor(self, rhs: Self) -> Self::Output {
    self.to_godot() | rhs.to_godot() 
    // if the via type implements BitOr, this can be used. Else ".ord()" may be needed
  }
}
```

**Comment by Bromeon** [comment]
`BitOr` is already implemented, see https://godot-rust.github.io/docs/gdext/master/godot/classes/object/struct.ConnectFlags.html?search=BitOr.

`ConnectFlags` may be marked as enum rather than bitfield in the GDExtension API? In that case we'd need to special-case it.

**Comment by Bromeon** [comment]
Closed because it's not a missing `BitOr` issue, but a badly defined `ConnectFlags` in Godot. I can see if a PR is possible for that, although it might be a breaking change and would have to wait until v0.3.
