### ISSUE TITLE
[suggestion] make #[signal] generate a function which can be called

### ISSUE THREAD

**Issue by walksanatora** [godot-rust/gdext#963]
I feel like since you have to write a `fn signal_name(args...)` I feel like a signal should be a callable method

**Comment by Houtamelo** [comment]
@walksanatora Some previous discussion on a related topic that's worth reading: https://github.com/godot-rust/gdext/issues/8

**Comment by Bromeon** [comment]
Please use the existing issue :slightly_smiling_face:
