### ISSUE TITLE
CollisionShape3d Debug Color breaks gdextension compatibility

### ISSUE THREAD

**Issue by TCROC** [godot-rust/gdext#966]
I opened this issue on the godot side as I believe this is where the fix is needed: https://github.com/godotengine/godot/issues/100313

The TL;DR; is:

Godot introduced some methods that are only available in editor and debug builds.  This breaks gdext for exporting release builds.  The simple workaround for now on the gdext side may be to check if we are "release" and not "editor".  Then bind to this methods.

**Comment by TCROC** [comment]
Put in a PR on the godot engine that fixes it 😎

https://github.com/godotengine/godot/pull/100317

**Comment by Bromeon** [comment]
I implemented a workaround in godot-rust that prevents the compile error, see
https://github.com/godot-rust/gdext/commit/275756e1ea599e16cf58a05818af180a1a6e47a5.

Also, the upstream PR has just been merged.

**Comment by TCROC** [comment]
@Bromeon Awesome!  Should we revert the workaround you put in since upstream merged in?  That way things match api compatibility of Godot?  Or do you want to keep the workaround in still?

**Comment by Bromeon** [comment]
@TCROC I guess we can. I wonder if everyone has updated to latest Godot yet :thinking:

Maybe I can make it part of a PR that's not yet merging very soon...

**Comment by TCROC** [comment]
@Bromeon sounds like a good plan to me! :)
