### ISSUE TITLE
How do you make common properties that are shared across different nodes?

### ISSUE THREAD

**Issue by TheColorRed** [godot-rust/gdext#985]
I am trying to make a struct that has common properties that will be shared across different types of nodes so that I don't have to remember to add all of them for each struct. So what I did was create a resource that has all the properties on it like this:

```rs
#[derive(GodotClass)]
#[class(init, base=Resource)]
pub struct CommonProperties {
  #[export]
  pub name: GString,
  #[export]
  #[init(val = 5.0)]
  speed: float,
}
```

Then I use that struct like this:

```rs
#[derive(GodotClass)]
#[class(init, base=Node3D)]
pub struct Object1 {
  #[export]
  common_properties: Gd<CommonProperties>,
}
```

However, I am getting an error saying that "name" doesn't exist:
> no field `name` on type `godot::prelude::Gd<CommonProperties>`

```rs
#[godot_api]
impl INode3D for Oject1 {
  fn ready(&mut self) {
    let name = self.common_properties.name.to_string();
    godot_print!("{name} has been created.");
  }
}
```

Is this the correct way to approach this task?

**Comment by Bromeon** [comment]
The section [_Bind guards_](https://godot-rust.github.io/docs/gdext/master/godot/obj/struct.Gd.html#bind-guards) explains how you can access data stored inside a `Gd<T>` :slightly_smiling_face: 

Btw, in case you're on Discord, you can also ask questions there in the `#help` channel!

**Comment by TheColorRed** [comment]
> Btw, in case you're on Discord, you can also ask questions there in the `#help` channel!

I am not on Discord, but I will check it out. Thanks for the help!

**Comment by TheColorRed** [comment]
Okay, I got this working, but I am not sure if this is a bug in Godot or the extension,

When ever I add a new property to the `Resource`, all the properties in the editor get reset back to their defaults.

**Comment by TheColorRed** [comment]
NVM, It was the editor, as by default it wasn't creating a "new" resource.
