### ISSUE TITLE
[FEATURE]: Ability to attach scripts to nodes

### ISSUE THREAD

**Issue by TheColorRed** [godot-rust/gdext#987]
I saw it in another gdextension library (J.E.N.O.V.A. for c++) that you can attach scripts to nodes instead of creating a whole new node, as it works just like you would attach a GDScript. This would be nice if that was supported.

![image](https://github.com/user-attachments/assets/b7299de0-4e39-4c6a-8f54-c33654e944f8)

**Comment by Bromeon** [comment]
This is partially supported through script instances, see [`godot::obj::script`](https://godot-rust.github.io/docs/gdext/master/godot/obj/script/index.html).

That said, it's not the primary workflow, and I personally won't be able to maintain scripting next to all the other priorities. In the past @TitanNano has helped a lot (and is the reason why so much exists at all right now :slightly_smiling_face:). Would you be interested in working on these parts?

**Comment by TitanNano** [comment]
There is also [godot-rust-script](https://github.com/titannano/godot-rust-script) that builds on gdext and allows for creating scripts in Rust.

**Comment by walksanatora** [comment]
@TheColorRed you can add scripts to nodes. it just involves a whole process of making a `ScriptLanguage`, then you need to make a `Script` class for your language which creates `ScriptInstance`s. an the `Script` also needs `ResourceFormatSaver` and `ResourceFormatLoaders` (and if you mess up any of these classes the engine *can* and probally *will* crash. eg: The `ResourceFormatLoader` not detecting `Script` as a valid type so your script gets loaded as a `TextFile` and immedeatly casuing a nullref and crashing when it cast it to `Script`)

**Comment by Bromeon** [comment]
Closing since this is already possible, and there's [godot-rust-script](https://github.com/titannano/godot-rust-script) to streamline the process.

For godot-rust itself, I see the focus for now on improving the respective APIs so that users are unblocked in implementing the missing parts, and there's less than can be done wrong. But there's already https://github.com/godot-rust/gdext/issues/970 to track this.
